- pkg/prow/config/config.go
- pkg/prow/hook/events.go
- pkg/webhook/webhook.go
also added debugging information on how many push hooks found
> fix: tidied up the wait group handling

- README.md
- charts/lighthouse/templates/deployment.yaml
- pkg/prow/config/config.go
- pkg/prow/github/client.go
- pkg/prow/plugins/plugins.go
- pkg/watcher/configmap_watcher.go
- pkg/webhook/webhook.go
we can later on replace that with watching `SourceRepository /
SourceRepositoryGroup / Scheduler` CRDs
> fix: lets watch the ConfigMaps directly for configuration changes

- pkg/prow/config/jobs.go
> fix: bug loading configurations from config maps

- go.mod
- go.sum
- pkg/prow/genfiles/genfiles.go
- pkg/prow/git/git.go
- pkg/prow/git/localgit/localgit.go
- pkg/prow/gitattributes/gitattributes.go
- pkg/prow/plugins/size/size_test.go
- pkg/webhook/webhook.go
and different git servers in general
> fix: fixes for GitHub Enterprise

- go.mod
- go.sum
- pkg/prow/config/config.go
- pkg/prow/plugins/plugins.go
- pkg/prow/plugins/skip/skip.go
- pkg/prow/plugins/trigger/generic-comment.go
- pkg/prow/plugins/trigger/pull-request.go
- pkg/prow/plugins/trigger/push.go
as a bitbucket namespace == the projectKey unlike the owner in the prow  config
> fix: handle bitbucket server Namespaces better

- pkg/plumber/constants.go
- pkg/plumber/fake/fake.go
- pkg/plumber/interface.go
- pkg/plumber/plumber.go
- pkg/plumber/types.go
- pkg/prow/config/config.go
- pkg/prow/config/jobs.go
- pkg/prow/config/tide.go
- pkg/prow/pjutil/filter.go
- pkg/prow/pjutil/pjutil.go
- pkg/prow/pjutil/pjutil_test.go
- pkg/prow/plugins/override/override.go
- pkg/prow/plugins/override/override_test.go
- pkg/prow/plugins/trigger/generic-comment_test.go
- pkg/prow/plugins/trigger/pull-request_test.go
- pkg/prow/plugins/trigger/push_test.go
- pkg/prow/plugins/trigger/trigger.go
- pkg/prow/plugins/trigger/trigger_test.go
* remove unnecessary data and Status
* renamed to avoid confusion that its a CRD - a Plumber implementation can make any kind of CRD it wants
#77
> fix: refactor PlumberJob

- charts/lighthouse/values.yaml
> fix: bump lighthouse image tag in chart

- Makefile
- charts/lighthouse/templates/deployment.yaml
so that if we change the hmac token we restart lighthouse
> fix: add checksum for secret

- charts/lighthouse/templates/tide-deployment.yaml
- charts/lighthouse/values.yaml
seems to restart a bit with the current settings ;)
> fix: use better liveness probe

- pkg/plumber/helpers.go
- pkg/prow/hook/events.go
- pkg/prow/plugins/override/override.go
- pkg/prow/plugins/override/override_test.go
- pkg/prow/plugins/plugins.go
- pkg/webhook/webhook.go
rahter than the global default factory
> fix: use the lighthouse servers factory to create metapipeline clients

- Dockerfile
- Dockerfile.tide
- jenkins-x.yml
to try work around odd failures on PRs lately
> fix: switch to building the binaries in the build pod

- pkg/webhook/webhook_test.go
This implements a test for the `ProcessWebhook` method in the webhook package. 
Fixes #352
> feat(tests): first spike of webhook unit tests

- pkg/webhook/test_data/test_config.yaml
- pkg/webhook/test_data/test_plugins.yaml
- pkg/webhook/webhook_test.go
This uses a faked k8s client and includes some dummy plugin & config files.
Fixes #360
> fix(tests): use faked k8s client in webhook tests

- bdd/ghe/ci.sh
- bdd/github/ci.sh
> chore: Update ci.shs for BDD tests to continue to work right

- bdd/github/ci.sh
- bdd/github/parameters.yaml
- jenkins-x-github.yml
> fix: Switch to new bot test user

- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
and make it easier to pass in more logging context for better tracing/observability
> fix: tone down error logging

- pkg/plumber/fake/fake.go
- pkg/prow/plugins/trigger/trigger.go
- pkg/prow/plugins/trigger/trigger_test.go
> fix: Report error status to provider if can't run metapipeline

- bdd/bbs/README.md
- bdd/bbs/ci.sh
- bdd/bbs/cluster.yaml
- bdd/bbs/jx-requirements.yml
- bdd/bbs/parameters.yaml
- bdd/gitlab/README.md
- bdd/gitlab/ci.sh
- bdd/gitlab/cluster.yaml
- bdd/gitlab/jx-requirements.yml
- bdd/gitlab/parameters.yaml
- jenkins-x-bbs.yml
- jenkins-x-gitlab.yml
> fix: Add BBS and Gitlab test contexts

- charts/lighthouse/templates/deployment.yaml
- charts/lighthouse/templates/tide-deployment.yaml
support kube api 1.16+
part of https://github.com/jenkins-x/jx/pull/6385
> fix: compatible with kube api 1.16+

- charts/lighthouse/templates/tide-role.yaml
> fix: Forgot to add tekton APIs to tide role

- charts/lighthouse/templates/tide-role.yaml
> fix: Forgot a few more permissions for the tide role

- go.sum
- pkg/tide/pipelinerun_monitor.go
> fix: Check for nil run status when dealing with Tekton race condition

- Makefile
- go.sum
- pkg/plumber/plumber.go
- pkg/plumber/types.go
- pkg/plumber/types_test.go
> fix: Pass Prow-style env vars to pipeline

- pkg/prow/plugins/trigger/generic-comment.go
> fix: FilterPresubmits needs to be the PR SHA, not its ref

- .whitesource.config
- jenkins-x-whitesource.yml
After this gets merged, it requires also https://github.com/jenkins-x/environment-tekton-weasel-dev/pull/411
in order to start being triggered on merged to master.
> feat: add a pipeline for whitesource dependencies scanning

- bdd/ghe/ci.sh
- bdd/ghe/jx-requirements.yml
- bdd/github/ci.sh
- bdd/github/jx-requirements.yml
- go.sum
- jenkins-x-ghe.yml
- jenkins-x-github.yml
I'm not 100% sure this will work right away, but I've added the secret, etc, so it should work.
> chore: Turn on lighthouse BDD suite and app lifecycle tests for GHE

- pkg/webhook/test_data/test_config.yaml
- pkg/webhook/test_data/test_plugins.yaml
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
> fix: Return 500 for unknown repositories when in GitHub App mode

- pkg/watcher/configmap_watcher.go
- pkg/webhook/webhook.go
I kinda hate all this logic - it's an ugly hodge-podge and I probably
_should_ just switch it back to mount-based, but I should really be
doing this here anyway. So...
fixes #627
> fix: Make sure we've synced the informer watcher for the webhook controller

- charts/lighthouse/values.yaml
Changing this broke stuff, so let's set a new variable instead.
> fix: Backwards-compatibility for image.repository value

- go.mod
- go.sum
- pkg/git/git.go
- pkg/keeper/keeper.go
- pkg/scmprovider/pull_requests.go
- pkg/webhook/webhook.go
Needed a go-scm fix.
fixes #666
fixes #667
fixes #668
> fix: Merge method for repo should be used

- go.mod
- go.sum
- pkg/repoowners/repoowners.go
- pkg/scmprovider/client.go
- pkg/scmprovider/fake/fake.go
- pkg/scmprovider/organizations.go
- pkg/webhook/webhook.go
> fix: Check org members, not just collabs, for approve rights

- pkg/webhook/webhook.go
That's kinda silly, and appears to cause sporadic nil pointers.
fixes #630
> fix: Stop creating a new launcher client for each webhook event

- go.mod
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/foghorn/controller.go
> fix: Properly finalize/default/validate config loaded via watcher

- cmd/foghorn/main.go
- go.mod
- pkg/foghorn/controller.go
- pkg/scmprovider/client.go
- pkg/scmprovider/issues.go
- pkg/scmprovider/reporter/reporter.go
- pkg/scmprovider/reporter/reporter_test.go
- pkg/util/constants.go
- pkg/webhook/webhook.go
> feat: Prow-style comments for failed builds in PRs with links

- cmd/gc/main.go
- go.mod
- go.sum
- pkg/keeper/keeper.go
- pkg/keeper/pipelinerun_monitor.go
- pkg/keeper/status.go
- pkg/repoowners/repoowners.go
- pkg/watcher/configmap_watcher.go
New version of Gosec just came out and it's got a new error that breaks Lighthouse, so let's fix it! And while we're here, bump go-scm.
> fix: Fix Gosec G601 failure

- go.mod
- go.sum
- pkg/scmprovider/issues.go
- pkg/scmprovider/organizations.go
- pkg/scmprovider/pull_requests.go
- pkg/scmprovider/repositories.go
- pkg/scmprovider/reviews.go
> fix: Get all pages of results for provider queries

- pkg/scmprovider/reviews.go
Picks up go-scm change to implement requesting and unrequesting
reviews, and a BDD test change to verify it.
fixes #708
> fix: Get /cc and /uncc to work

- bdd/bbs/ci.sh
- bdd/ghe/ci.sh
- bdd/github/ci.sh
- bdd/gitlab/ci.sh
> fix: Copy jx dependencies into temp JX_HOME

- pkg/scmprovider/issues.go
- pkg/scmprovider/pull_requests.go
I saw this wasn't implemented but then forgot about it. So let's fix it.
fixes #730
> fix: Implement /close

- go.mod
- go.sum
- pkg/scmprovider/issues.go
- pkg/scmprovider/pull_requests.go
> fix: Implement /reopen properly

- bdd/bbs/ci.sh
- bdd/ghe/ci.sh
- bdd/github/ci.sh
- bdd/gitlab/ci.sh
- cmd/keeper/main.go
- go.mod
- go.sum
- jenkins-x-bbs.yml
- pkg/jobutil/jobutil.go
- pkg/keeper/status.go
- pkg/plugins/override/override.go
- pkg/plugins/override/override_test.go
- pkg/plugins/size/size.go
- pkg/scmprovider/client.go
- pkg/scmprovider/labels.go
- pkg/scmprovider/organizations.go
- pkg/scmprovider/reporter/reporter.go
A number of fixes and changes to get BitBucket Server support, using labels embedded in a comment, to work. 
There'll be a followup to this to switch the bdd-jx back to normal, once this has merged and bdd-jx has updated accordingly.
> feat: BitBucket Server support (preview)

- bdd/bbs/ci.sh
- bdd/ghe/ci.sh
- bdd/github/ci.sh
- bdd/gitlab/ci.sh
> test: Switch back to standard bdd-jx

- charts/lighthouse/values.yaml
> fix: Increase Keeper memory and CPU limits

- go.sum
- pkg/webhook/events.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
> fix: Handle GitHub and BitBucket Server review approvals same as /approve

- charts/lighthouse/templates/gc-jobs-cj.yaml
- charts/lighthouse/values.yaml
Stumbled across this after I reviewed #778.
fyi @vbehar. =)
> fix: Correct path for gc-jobs command in cronjob

- pkg/webhook/webhook.go
> fix: Stop sending version info for root URL

- pkg/util/constants.go
- pkg/util/externalplugins.go
- pkg/webhook/events.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
For whatever reason, this functionality wasn't included originally, so let's add it.
> chore: Add external plugin support like Prow

- pkg/foghorn/plugins.go
> fix: Embed plugins into foghorn binary to prevent unknown plugin errors

- pkg/apis/lighthouse/register.go
- pkg/apis/lighthouse/v1alpha1/types.go
- pkg/engines/tekton/activity.go
- pkg/engines/tekton/controller.go
- pkg/engines/tekton/controller_test.go
- pkg/engines/tekton/test_data/activity/failed_single_task/pr.yaml
- pkg/engines/tekton/test_data/activity/failed_single_task/record.yaml
- pkg/engines/tekton/test_data/activity/running_multiple_tasks/pr.yaml
- pkg/engines/tekton/test_data/activity/running_multiple_tasks/record.yaml
- pkg/engines/tekton/test_data/activity/running_single_task/pr.yaml
- pkg/engines/tekton/test_data/activity/running_single_task/record.yaml
- pkg/engines/tekton/test_data/activity/successful_multiple_tasks/pr.yaml
- pkg/engines/tekton/test_data/activity/successful_multiple_tasks/record.yaml
- pkg/engines/tekton/test_data/activity/successful_single_task/pr.yaml
- pkg/engines/tekton/test_data/activity/successful_single_task/record.yaml
- pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml
- pkg/engines/tekton/test_data/controller/update-job/expected-lhjob.yml
> fix(tekton): Better PR and stage naming, set owner refs for cleanup

- cmd/keeper/main.go
- pkg/foghorn/controller.go
- pkg/util/scmclient.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
> chore: Move various env-var-related functions to util

- charts/lighthouse/templates/foghorn-role.yaml
- charts/lighthouse/templates/keeper-role.yaml
- charts/lighthouse/templates/webhooks-role.yaml
- cmd/foghorn/main.go
- cmd/keeper/main.go
- cmd/tektoncontroller/main.go
- go.mod
- go.sum
- pkg/config/config.go
- pkg/engines/tekton/controller.go
- pkg/foghorn/controller.go
- pkg/plugins/config.go
- pkg/plugins/config_test.go
- pkg/plugins/updateconfig/updateconfig.go
- pkg/plugins/updateconfig/updateconfig_test.go
- pkg/util/scmclient.go
- pkg/util/stopper.go
- pkg/watcher/configmap_watcher.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
Jenkins X doesn't use this, but non-jx usage definitely would like to!
> feat: Add back the Prow-style config updater plugin

- pkg/foghorn/plugins.go
- pkg/webhook/plugins.go
> fix: Forgot to import config-updater into binaries

- pkg/plugins/plugins.go
> fix: Need to pass kube client to plugin agent

- pkg/keeper/keeper.go
- pkg/keeper/keeper_test.go
> feat: Comment on PRs that failed to merge

- bdd/tekton/ci.sh
- test/e2e/tekton_test.go
- test/e2e/test_data/passingRepoScript.sh
- test/e2e/test_data/tekton/pipelineAndTask.tmpl.yaml
> fix: Set git-batch-merge depth parameter in test

- README.md
- bdd/bbs/ci.sh
- bdd/capture-failed-pod-logs.sh
- bdd/ghe/ci.sh
- bdd/github/ci.sh
- bdd/gitlab/ci.sh
- bdd/tekton/ci.sh
- charts/lighthouse/templates/config-cm.yaml
- charts/lighthouse/templates/plugins-cm.yaml
- charts/lighthouse/values.yaml
- docs/INSTALL.md
- test/e2e/tekton_test.go
- test/e2e/test_data/tekton/pipelineAndTask.tmpl.yaml
> feat: Add non-jx install docs

- charts/lighthouse/templates/plugins-cm.yaml
- test/e2e/test_data/example-plugins.tmpl.yml
> chore: Add a few more plugins to the default setup

- README.md
- pkg/apis/lighthouse/v1alpha1/repoconfig_config_types.go
- pkg/plugins/updateconfig/test_data/invalid-config.yaml
- pkg/plugins/updateconfig/test_data/invalid-yaml.yaml
- pkg/plugins/updateconfig/test_data/valid-config.yaml
- pkg/plugins/updateconfig/updateconfig.go
- pkg/plugins/updateconfig/updateconfig_test.go
> feat: Validate config-updater changes before merging

- pkg/plugins/approve/approve.go
- pkg/plugins/approve/approvers/owners.go
- pkg/plugins/updateconfig/updateconfig.go
- pkg/plugins/updateconfig/updateconfig_test.go
- pkg/util/scmclient.go
> feat: Make config-updater file name in comment a link

- charts/lighthouse/templates/NOTES.txt
This PR improves chart NOTES.TXT.
> chore: Improve chart notes

- Makefile
- jenkins-x.yml
> chore: Add check of fmt and other targets not having modified code

- docs/PLUGINS.md
- docs/plugins/wip.md
This PR adds `wip` plugin docs.
> docs: Add wip plugin docs

- docs/PLUGINS.md
- docs/plugins/shrug.md
This PR adds shrug plugin docs.
> docs: Add shrug plugin docs

- docs/PLUGINS.md
- docs/plugins/size.md
This PR adds size plugin docs.
> docs: Add size plugin docs

- docs/PLUGINS.md
- docs/plugins/welcome.md
This PR adds welcome plugin docs.
> docs: Add welcome plugin docs

- charts/lighthouse/templates/plugins-cm.yaml
- docs/PLUGINS.md
- pkg/plugins/config.go
- pkg/repoconfig/merge/test_data/simple/expected-plugins.yaml
- pkg/repoconfig/merge/test_data/simple/source-plugins.yaml
- pkg/webhook/test_data/test_plugins.yaml
- test/e2e/test_data/example-plugins.tmpl.yml
This PR removes the slack plugin config (dead code)
> chore: Remove slack plugin config (dead code)

- pkg/apis/lighthouse/v1alpha1/types.go
- pkg/apis/lighthouse/v1alpha1/types_test.go
- pkg/engines/tekton/controller.go
- pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-pr.yml
- pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml
> chore: Add REPO_URL and PULL_PULL_REF Tekton parameters

- docs/PLUGINS.md
- docs/plugins/hold.md
This PR adds hold plugin docs.
> docs: Add hold plugin docs

- pkg/util/scmclient.go
> fix: Check for nil of config, not getter

- pkg/apis/lighthouse/v1alpha1/types.go
- pkg/apis/lighthouse/v1alpha1/zz_generated.deepcopy.go
- pkg/config/jobs.go
- pkg/engines/tekton/controller.go
- pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-lhjob.yml
- pkg/engines/tekton/test_data/controller/start-batch-pullrequest/observed-lhjob.yml
- pkg/engines/tekton/test_data/controller/start-pullrequest/expected-lhjob.yml
- pkg/engines/tekton/test_data/controller/start-pullrequest/observed-lhjob.yml
- test/e2e/tekton_test.go
This PR adds `pipeline_run_params` support to lighthouse job.
Work in progress
> feat: Add pipeline_run_params support to lighthouse job

- pkg/util/externalplugins.go
- pkg/util/externalplugins_test.go
> fix: adding nil check for pluginConfig.Config() in util.ExternalPluginsForEvent

- cmd/foghorn/main.go
- cmd/tektoncontroller/main.go
- go.mod
- go.sum
- pkg/foghorn/controller.go
- pkg/foghorn/controller_test.go
- pkg/foghorn/test_data/no-status-change/expected-lhjob.yml
- pkg/foghorn/test_data/no-status-change/observed-lhjob.yml
- pkg/foghorn/test_data/status-change/expected-lhjob.yml
- pkg/foghorn/test_data/status-change/observed-lhjob.yml
Also fixes #941 while I'm here.
> chore: Switch foghorn controller to use controller-runtime

- Dockerfile.webhooks
- Makefile
- cmd/webhooks/main.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
> refactor: Get rid of cobra stuff in webhooks

- docs/config/Lighthouse config.md
- pkg/config/config.go
- pkg/jobutil/jobutil.go
- pkg/jobutil/jobutil_test.go
This PR removes JenkinsOperator and most of Plank config.
> chore: remove most of Plank config

- charts/lighthouse/templates/config-cm.yaml
- config.yaml
- docs/config/Lighthouse config.md
- pkg/config/config.go
- pkg/foghorn/controller_test.go
- pkg/repoconfig/merge/test_data/simple/expected-config.yaml
- pkg/repoconfig/merge/test_data/simple/source-config.yaml
- pkg/webhook/test_data/test_config.yaml
- test/e2e/test_data/example-config.tmpl.yml
> chore: remove Gerrit config

- Makefile
- cmd/foghorn/main.go
- cmd/gc/main.go
- cmd/tektoncontroller/main.go
- pkg/clients/clients.go
fix: allow to run controllers locally
This reverts commit bb2e6479
fixes #971
> fix: allow to run controllers locally

- config.yaml
- go.sum
- pkg/config/config_test.go
- pkg/config/job/config.go
- pkg/config/job/periodic.go
- pkg/config/lighthouse/config.go
- pkg/foghorn/controller_test.go
- pkg/repoconfig/merge/test_data/simple/expected-config.yaml
- pkg/repoconfig/merge/test_data/simple/source-config.yaml
This PR removes deprecated config elements.
> chore: remove deprecated config elements

- bdd/bbs/ci.sh
- bdd/ghe/ci.sh
- bdd/github/ci.sh
- bdd/gitlab/ci.sh
- bdd/tekton/ci.sh
- charts/lighthouse/Makefile
> fix: Stop echoing everything in bdd tests' ci.sh files

- charts/lighthouse/README.md
- charts/lighthouse/values.yaml
This PR adds annotations in chart `values.yaml` to improve generated chart docs.
> chore: Improve chart docs

- charts/lighthouse/README.md
- charts/lighthouse/templates/keeper-deployment.yaml
- charts/lighthouse/values.yaml
> fix: Make keeper image pull policy configuration consistent

- docs/INSTALL.md
> docs: Install docs update

- OWNERS
- jenkins-x.yml
No one's actually merging them, so let's stop bothering to create them.
> chore: Stop creating update PRs on jx.git on release

- pkg/keeper/keeper.go
- pkg/keeper/keeper_test.go
- pkg/keeper/status.go
- pkg/keeper/status_test.go
> feat: Set Keeper status desc for green PRs blocked by retests

- pkg/plugins/dog/dog.go
- pkg/plugins/dog/dog_test.go
- pkg/plugins/plugins.go
This PR refactors the dog plugin.
It adds separate commands for all commands regular expressions `/this-is-fine`, `/this-is-not-fine` and `/this-is-unbearable`.
> refactor: dog plugin

- pkg/plugins/dog/dog.go
- pkg/plugins/dog/dog_test.go
- pkg/plugins/plugins.go
- pkg/plugins/shrug/shrug.go
- pkg/plugins/shrug/shurg_test.go
- pkg/plugins/yuks/yuks.go
- pkg/plugins/yuks/yuks_test.go
This PR refactors the shrug and yuks plugins.
It adds separate commands for all commands regular expressions.
> refactor: shrug and yuks plugins

- pkg/plugins/milestonestatus/milestonestatus.go
- pkg/plugins/milestonestatus/milestonestatus_test.go
This PR refactors the milestonestatus plugin
> refactor: milestonestatus plugin

- pkg/plugins/dog/dog.go
- pkg/plugins/dog/dog_test.go
- pkg/plugins/plugins.go
- pkg/plugins/pony/pony.go
- pkg/plugins/pony/pony_test.go
- pkg/plugins/shrug/shrug.go
- pkg/plugins/shrug/shurg_test.go
- pkg/plugins/stage/stage.go
- pkg/plugins/stage/stage_test.go
- pkg/plugins/yuks/yuks.go
- pkg/plugins/yuks/yuks_test.go
This PR refactors stage and pony plugins
> refactor: stage and pony plugins

- pkg/plugins/label/label.go
- pkg/plugins/label/label_test.go
This PR refactors the label plugin.
> refactor: label plugin

- pkg/plugins/help/help.go
- pkg/plugins/help/help_test.go
- pkg/plugins/plugins.go
This PR refactors the help plugin.
> refactor: help plugin

- pkg/plugins/approve/approve.go
- pkg/plugins/help/help.go
- pkg/plugins/help/help_test.go
- pkg/plugins/plugins.go
This PR refactors approve plugin.
> refactor: approve plugin

- pkg/plugins/lifecycle/close.go
- pkg/plugins/lifecycle/close_test.go
- pkg/plugins/lifecycle/lifecycle.go
- pkg/plugins/lifecycle/lifecycle_test.go
- pkg/plugins/lifecycle/reopen.go
- pkg/plugins/lifecycle/reopen_test.go
This PR refactors the lifecycle plugin.
> refactor: lifecycle plugin

- pkg/plugins/lgtm/lgtm.go
- pkg/plugins/lgtm/lgtm_test.go
This PR refactors the lgtm plugin.
> refactor: lgtm plugin

- pkg/plugins/milestone/milestone.go
- pkg/plugins/milestone/milestone_test.go
This PR refactors the milestone plugin.
The `Milestone` service doesn't exist in `go-scm` though, not sure if this plugin works ?
> refactor: milestone plugin

- pkg/plugins/override/override.go
- pkg/plugins/override/override_test.go
This PR refactors the override plugin.
> refactor: override plugin

- pkg/plugins/trigger/generic-comment.go
- pkg/plugins/trigger/trigger.go
This PR refactors the trigger plugin.
This is the last plugin refactor of the list 🎉
> refactor: trigger plugin

- pkg/plugins/hold/hold.go
- pkg/plugins/hold/hold_test.go
This PR refactors the hold plugin.
> refactor: hold plugin

- pkg/plugins/milestone/milestone.go
- pkg/scmprovider/client.go
- pkg/scmprovider/fake/fake.go
- pkg/scmprovider/legacy_helpers.go
- pkg/scmprovider/milestones.go
> fix: Actually enable the milestone plugin.

- pkg/plugins/plugins.go
This PR removes some obsolete plugins code.
Fixes https://github.com/jenkins-x/lighthouse/issues/1057
> chore: remove obsolete plugins code

- docs/INSTALL.md
This PR adds trigger plugins in doc.
see https://github.com/zxDiscovery/lighthouse/blob/master/docs/INSTALL.md
> docs: Update plugins.yaml to add trigger plugin

- charts/lighthouse/templates/gc-jobs-cj.yaml
- docker/foghorn/Dockerfile
- docker/gc/Dockerfile
- docker/jenkins/Dockerfile
- docker/keeper/Dockerfile
- docker/tekton/Dockerfile
- docker/webhooks/Dockerfile
This PR changes Dockerfiles to that all the different bits of lighthouse can run as a non-root user.
> fix: run as an unprivileged user

- charts/lighthouse/README.md
- charts/lighthouse/templates/webhooks-deployment.yaml
- charts/lighthouse/values.yaml
in the webhooks pods, add support for:
- nodeSelector
- affinity
- tolerations
> fix: add more fields to webhook chart deployment

- charts/lighthouse/README.md
- charts/lighthouse/values.yaml
> chore: Set the default replica count for webhooks to 1

- pkg/engines/jenkins/controller.go
- pkg/engines/jenkins/jenkins.go
fixes #1073
(P.S. There will be a e2e test for this in pr #1078)
> fix: Ensure status URL gets updated in LighthouseJob

- dependency-matrix/matrix.md
- dependency-matrix/matrix.yaml
> chore: Remove obsolete dependency-matrix directory

- pkg/triggerconfig/merge/merge.go
> fix: possible concurrent modification errors using in repo config

- charts/lighthouse/README.md
- charts/lighthouse/templates/tekton-controller-deployment.yaml
- charts/lighthouse/values.yaml
- cmd/tektoncontroller/main.go
- pkg/engines/tekton/controller.go
- pkg/engines/tekton/controller_test.go
> fix: support other UIs than just tekton dashboard for reporting

- Makefile
- bdd/jenkins/ci.sh
- jenkins-x-tekton.yml
- pkg/plugins/override/override_test.go
- pkg/scmprovider/repositories.go
- test/e2e/helpers.go
Once this is ready, I'll disable the `github` and `gitlab` contexts, since those will be covered by the `jenkins` and `tekton` contexts respectively.
> chore: Switch tekton context to use GitLab

- pkg/triggerconfig/inrepo/calculate.go
Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>
> fix: handle case when master or new PR don't have jx config

- pkg/triggerconfig/inrepo/calculate.go
- pkg/triggerconfig/inrepo/calculate_test.go
- pkg/triggerconfig/inrepo/load_triggers.go
- pkg/triggerconfig/inrepo/load_triggers_test.go
- pkg/triggerconfig/inrepo/scm_provider_client.go
so that the in-repo logic works with whatever the main branch is
fixes #1110
> fix: lets remove the hard coding of master branch

- pkg/triggerconfig/merge/merge.go
it looks like we were incorrectly updating the existing presubmit/postsubmits when merging - we were using the index variable from the wrong for loop ;)
> fix: bug in merge logic

- pkg/triggerconfig/inrepo/load_triggers.go
Fixes https://github.com/jenkins-x/lighthouse/issues/1126
> fix: Make inrepo triggers config filename consistent

- pkg/keeper/status.go
- pkg/keeper/status_test.go
Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>
> fix: log failure raison since not possible to sent to gitlab

- pkg/triggerconfig/inrepo/default_parameters.go
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs-sub-dir/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-append-steps/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-prepend-steps/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-without-params/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/taskrun/expected.yaml
for values only supplied via PR pipelines to avoid missing parameter errors on release pipelines
> fix: add better default value

- pkg/triggerconfig/inrepo/default_parameters.go
- pkg/triggerconfig/inrepo/load_triggers.go
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs-sub-dir/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-append-steps/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-prepend-steps/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-without-params/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/taskrun/expected.yaml
- pkg/util/error_markdown.go
- pkg/util/error_markdown_test.go
- pkg/webhook/events.go
as its probably caused by a bad `triggers.yaml` file in the Pull Request
> fix: add comment on PR if we cannot create Agent

- charts/lighthouse/Makefile
- charts/lighthouse/README.md
- charts/lighthouse/values.yaml
tried editing https://github.com/jenkins-x/lighthouse/pull/1152 to also regenerate the chart readme to see if that passes the CI checks
> chore: fix missing value in helm chart v2

- go.mod
- pkg/filebrowser/git_file_browser.go
- pkg/filebrowser/git_file_browser_test.go
- pkg/filebrowser/interface.go
- pkg/filebrowser/scm_file_browser.go
- pkg/filebrowser/scm_provider_client.go
- pkg/git/v2/client_factory.go
- pkg/git/v2/executor.go
- pkg/git/v2/executor_test.go
- pkg/git/v2/fakes.go
- pkg/git/v2/interactor.go
- pkg/git/v2/interactor_test.go
- pkg/git/v2/publisher.go
- pkg/git/v2/publisher_test.go
- pkg/git/v2/remote.go
- pkg/git/v2/remote_test.go
- pkg/keeper/keeper.go
- pkg/triggerconfig/inrepo/calculate.go
- pkg/triggerconfig/inrepo/calculate_test.go
- pkg/triggerconfig/inrepo/load_integration_test.go
- pkg/triggerconfig/inrepo/load_triggers.go
- pkg/triggerconfig/inrepo/load_triggers_test.go
- pkg/triggerconfig/inrepo/scm_provider_client.go
- pkg/webhook/create_agent.go
- pkg/webhook/events.go
- pkg/webhook/webhook.go
lets setup the agent when using in-repo calls upfront rather than repeating for each plugin
> fix: reduce the number of github API calls

- bdd/bbs/ci.sh
- bdd/ghe/ci.sh
- bdd/github/ci.sh
- bdd/gitlab/ci.sh
- init-helm.sh
- jenkins-x.yml
> fix: Deal with Helm stable chart URL change

- pkg/keeper/githubapp/factory.go
Fixes https://github.com/jenkins-x/lighthouse/issues/1182
> fix: provide auth token early for gitea as it is required

- pkg/git/v2/client_factory.go
- pkg/git/v2/interactor.go
- pkg/git/v2/remote.go
- pkg/webhook/webhook.go
fix: remove duplicate log line
fix: log an error that isnt logged by the caller
feat: support http git urls -  Support http urls by introducing a Scheme field
> feat: webhook support http urls with git file browser

- charts/lighthouse/templates/gc-jobs-cj.yaml
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
> feat: allow user to specify pod annotations for gc job

- go.mod
- go.sum
- pkg/triggerconfig/inrepo/load_integration_test.go
- pkg/triggerconfig/inrepo/load_triggers.go
- pkg/triggerconfig/inrepo/load_triggers_test.go
- pkg/triggerconfig/inrepo/test_data/load_url/foo.yaml
> feat: allow in-repo triggers to specify a URL for the source so we can easily trigger remote managed pipeline definitions

- pkg/plugins/size/size.go
If the scm provider does not provide additions and subtractions try to calculate it from the patch diff.
> fix: size plugin - check patch for backup size

- pkg/plugins/approve/approve.go
> fix: allow labels like Approved by making comparision in lower case

- pkg/keeper/status.go
- pkg/keeper/status_test.go
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
> fix: keeper status case insensitive labels

- charts/lighthouse/README.md
- charts/lighthouse/values.yaml
the values.yaml had a bad indentation for the foghorn.resources.requests
this change fixes this issue
> fix: correct chart values indentation for foghorn.resources.requests

- pkg/git/v2/interactor.go
> chore: tone down logging to debug level

- pkg/scmprovider/issues.go
> fix: add exception handle for scm response body

- charts/lighthouse/README.md
- charts/lighthouse/templates/foghorn-deployment.yaml
- charts/lighthouse/templates/hmacsecret.yaml
- charts/lighthouse/templates/webhooks-deployment.yaml
- charts/lighthouse/values.yaml
> chore: lets allow the hmac token to be disabled

- charts/lighthouse/templates/foghorn-deployment.yaml
- charts/lighthouse/templates/jenkins-controller-deployment.yaml
- charts/lighthouse/templates/keeper-deployment.yaml
- charts/lighthouse/templates/tekton-controller-deployment.yaml
- charts/lighthouse/templates/webhooks-deployment.yaml
- charts/lighthouse/templates/webhooks-ingress.yaml
> fix: remove the old draft labels

- pkg/triggerconfig/inrepo/default_parameters.go
- pkg/triggerconfig/inrepo/load_pipelinerun.go
- pkg/triggerconfig/inrepo/load_pipelinerun_test.go
- pkg/triggerconfig/inrepo/params.go
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-all-steps/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-custom-param-task/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-custom-param/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-add-custom-explict/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-add-custom/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-custom-git/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-custom-git/source.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-explicit/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-multiple-copies/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-override-resources/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-override/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-version-stream/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-task-and-steps/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/expected2.yaml
- pkg/triggerconfig/inrepo/uses_resolver.go
and ensure we properly inherit parameters from Task -> PipelineRun when using a Task and ensuring we add the parameters to the PipelineRun
> fix: better validation of uses pipelines

- go.sum
- pkg/filebrowser/fake/fake_file_browser.go
- pkg/filebrowser/git_file_browser.go
- pkg/triggerconfig/inrepo/load_triggers.go
- pkg/triggerconfig/inrepo/load_triggers_test.go
- pkg/triggerconfig/inrepo/test_data/empty_dir/README.md
> fix: lets not fail if a repo has no triggers dir

- go.sum
- pkg/triggerconfig/inrepo/params.go
- pkg/triggerconfig/inrepo/test_data/jenkins-x/jx3-pipeline-catalog/refs/1d39235ee9235d7d52d4025a8e59cb8bda04306a/packs/javascript-selenium/.lighthouse/jenkins-x/pullrequest.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-inherit-sidecar/README.md
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-inherit-sidecar/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-inherit-sidecar/source.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-with-sidecar/README.md
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-with-sidecar/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-with-sidecar/source.yaml
- pkg/triggerconfig/inrepo/uses_resolver.go
> fix: preserve sidecars with in repo pipelines

- pkg/keeper/keeper.go
so that we can configure which repos we disable the triggering
> fix: allow the trigger disable to be per repo

- charts/lighthouse/templates/jenkins-controller-deployment.yaml
> fix: chart syntax errors

- pkg/keeper/keeper.go
> chore: fix a minor typo

- pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-pr.yml
- pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml
- pkg/engines/tekton/test_data/controller/start-push/expected-pr.yml
- pkg/engines/tekton/utils.go
- pkg/jobutil/jobutil.go
- pkg/jobutil/jobutil_test.go
- pkg/webhook/create_agent.go
so its easier to find the lighthousejob you want for a given repo/context
> fix: lets add a nicer default name for LighthouseJobs

- pkg/filebrowser/git_file_browser.go
lets make sure we always fetch to avoid caching bugs
> fix: caching bug for release branches

- charts/lighthouse/README.md
- pkg/webhook/create_agent.go
- pkg/webhook/events.go
as this can take a little while
> fix: make configAgent creation async

- cmd/poller/main.go
- pkg/poller/poller.go
so that we get a better liveness probe
> fix: listen on http port

- cmd/poller/main.go
- pkg/filebrowser/git_file_browser.go
- pkg/git/v2/interactor.go
- pkg/git/v2/no_mirror_client_factory.go
- pkg/poller/poller.go
- pkg/webhook/webhook.go
> fix: avoid git mirroring and fix detecting of new releases

- docs/install_lighthouse_with_tekton.md
And remove the "create configMap" part to avoid Helm complaining.
> chore: fix typo in tekton quickstart.

- pkg/engines/tekton/controller_test.go
- pkg/engines/tekton/test_data/controller/debug-pr/expected-lhjob.yml
- pkg/engines/tekton/test_data/controller/debug-pr/expected-pr.yml
- pkg/engines/tekton/test_data/controller/debug-pr/observed-lhjob.yml
- pkg/engines/tekton/utils.go
so we can filter by PR numbers or release branches for breakpoints
> fix: better support for pipeline branch names

- OWNERS
- pkg/config/keeper/query.go
- pkg/config/keeper/query_test.go
- pkg/keeper/keeper.go
> fix: skip check on repo length to support nested gitlab repos

- pkg/repoowners/repoowners.go
- pkg/repoowners/repoowners_test.go
For organizations with many repositories it would make sense to refer to other repos to find OWNERS_ALIASES files in.
This PR implements the added field foreignAliases.
So an example OWNERS_ALIASES could look like
```
aliases:
best-approvers:
- you
- me
foreignAliases:
- name: a-repo
- org: another-org
name: the-repo
- org: yaorg
name: yarepo
ref: special-branch
```
org defaults to current organization
ref default to HEAD
If an alias is present in several sources the members are merged.
Fixes #1382
> feat: Use OWNERS_ALIASES files from other repos

- charts/lighthouse/README.md
- charts/lighthouse/templates/webhooks-ingress.yaml
- charts/lighthouse/values.yaml
Add support for ingress class name and stable ingress if available
> feat: Add ingress class name and upgrade to stable ingress

- charts/lighthouse/values.yaml
- cmd/poller/main.go
- pkg/poller/poller.go
This PR allows the period between release and pull request polls to be specified separately.
> feat: Support poller release and pull request periods

- pkg/jobutil/jobutil.go
- pkg/jobutil/jobutil_test.go
- pkg/plugins/trigger/trigger.go
> fix: keep group in lj label for nested gitlab repos

- charts/lighthouse/README.md
- charts/lighthouse/templates/webhooks-role.yaml
- charts/lighthouse/values.yaml
- Allow running lighthouse without cluster scoped permissions
> feat: Allow running lighthouse in namespace scope

- go.mod
- go.sum
- pkg/poller/poller.go
- pkg/scmprovider/pull_requests.go
> chore: bump go-scm to 1.11.4

- go.mod
- go.sum
> refactor: upgrade to go 1.17

- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
> fix: remove resource request from step template

- .github/workflows/codeql-analysis.yml
- .lighthouse/jenkins-x/pullrequest.yaml
> refactor: enable codeql alerts

- docker/foghorn/Dockerfile
- docker/gc/Dockerfile
- docker/jenkins/Dockerfile
- docker/keeper/Dockerfile
- docker/poller/Dockerfile
- docker/tekton/Dockerfile
- docker/webhooks/Dockerfile
alpine 3.12 reached it's EOL on May 1, 2022. See: https://endoflife.date/alpine
> refactor: upgrade alpine base image to 3.16

- go.mod
- go.sum
- pkg/webhook/create_agent.go
- pkg/webhook/events.go
This is needed because of a recent change to go-scm.
> fix: change checks to see if comment event is from PR

- pkg/git/git.go
Fixes:
```
{"Branch":"main","Clone":"https://gitlab.com/org/sub-group/sub-project.git","ID":"40115633","Link":"https://gitlab.com/org/sub-group/sub-project","Name":"sub-group/sub-project","Namespace":"org","Webhook":"pull_request","author":"Blank","error":"failed to clone org/sub-group/sub-project: mkdir /tmp/git2762905459/sub-group/sub-project: no such file or directory","level":"error","msg":"Error handling GenericCommentEvent.","org":"org","pr":37,"repo":"sub-group/sub-project","time":"2022-10-12T17:32:19Z","url":"https://gitlab.com/org/sub-group/sub-project/-/merge_requests/37"}
```
> Support GitLab nested groups

- pkg/triggerconfig/inrepo/load_pipelinerun.go
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-finally-uses/README.md
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-finally-uses/common.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-finally-uses/expected.yaml
- pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-finally-uses/source.yaml
https://kubernetes.slack.com/archives/C9MBGQJRH/p1666717135265409
Finally task could not recognize `image: uses:sourceURI` 
This PR makes this possible now
> chore: processUsesSteps now handle ps.Finally tasks too

- docker/foghorn/Dockerfile
- docker/gc/Dockerfile
- docker/jenkins/Dockerfile
- docker/keeper/Dockerfile
- docker/poller/Dockerfile
- docker/tekton/Dockerfile
- docker/webhooks/Dockerfile
Bump alpine version to fix the CVEs:
- CVE-2022-41903
-  CVE-2022-23521
> refactor: Update alpine base image to 3.17

- .lighthouse/jenkins-x/release.yaml
Trying to get the lighthouse pipeline working
> chore: upgrade jx changelog pipeline version

- pkg/keeper/keeper.go
> fix: skip repo that can't queried

- pkg/config/job/presubmit.go
- pkg/plugins/trigger/generic-comment_test.go
I noticed that this test
a) Tested the wrong thing
b) Expected the wrong result
fixes jenkins-x/jx#8477
> reenable manual trigger despite run_if_changed not matching

- pkg/plugins/trigger/pull-request.go
Supersedes https://github.com/jenkins-x/lighthouse/pull/1602
> chore: this warning isn't actionable (I think) so let's remove it until it is
