go.mod, go.sum, pkg/webhook/webhook.go
as some git providers like gitlab sometimes pass in the owner/repo after the hook path
=> fix: lets allow nested paths within the webhook URLs

go.mod, go.sum, pkg/plumber/fake/fake.go, pkg/plumber/interface.go, pkg/plumber/plumber.go, pkg/prow/plugins/override/override.go, pkg/prow/plugins/override/override_test.go, pkg/prow/plugins/plugins.go, pkg/prow/plugins/trigger/push.go, pkg/prow/plugins/trigger/trigger.go
This includes support for using the plugin agent to access a cached metapipeline client, although this approach is not implemented in all cases.
=> fix: Switch to metapipeline client

jenkins-x.yml
Without this, chart deploys on release are failing.
=> fix: Get chartmuseum password, not just user

dependency-matrix/matrix.md, dependency-matrix/matrix.yaml, go.mod, go.sum
Update [jenkins-x/go-scm](https://github.com/jenkins-x/go-scm) from v1.5.25 to 1.5.26
Command run was `jx step create pr go --name github.com/jenkins-x/go-scm --version 1.5.26 --build make build --repo https://github.com/jenkins-x/lighthouse.git`
=> chore(deps): bump https://github.com/jenkins-x/go-scm from v1.5.25 to 1.5.26

pkg/plumber/helpers.go, pkg/prow/hook/events.go, pkg/prow/plugins/override/override.go, pkg/prow/plugins/plugins.go, pkg/webhook/webhook.go
to avoid unnecessary creation of the clients and speed up processing plugins
=> fix: lets try to eagerly create metapipeline clients

OWNERS
I am not currently working on JX/lighthouse, but sometimes I get randomly
assigned to review PRs and such. Seems best to remove myself from
OWNERS so that current maintainers are the ones getting assigned as
reviewers instead.
CC @abayer for review
=> chore: Remove @dwnusbaum from OWNERS

go.sum, pkg/prow/plugins/trigger/trigger.go
in case the bot user can't query the members of an org etc
=> fix: lets default to the current bot user being trusted

jenkins-x-bbs.yml, jenkins-x-ghe.yml, jenkins-x-github.yml, jenkins-x-gitlab.yml
Otherwise these will go stale and eventually not work with any changes
we may need to make re: `jx-requirements.yml`.
=> fix: Always use latest builder-* images in BDD pipelines

charts/lighthouse/values.yaml
The ingress resources are statically created by jxboot-resources chart.
See https://github.com/jenkins-x-charts/jxboot-resources/blob/master/jxboot-resources/templates/700-hook-ing.yaml
and https://github.com/jenkins-x-charts/jxboot-resources/blob/master/jxboot-resources/templates/700-tide-ing.yaml
This is to prevent that the ingress resources gets accidentally recreated wthen exposecontroller
is executed in the namespace where the Lighthouse is deployed.
=> fix: remove the expose-controller annotations on hook and tide services

bdd/bbs/ci.sh, bdd/bbs/jx-requirements.yml, bdd/ghe/ci.sh, bdd/ghe/jx-requirements.yml, bdd/github/ci.sh, bdd/github/jx-requirements.yml, bdd/gitlab/ci.sh, bdd/gitlab/jx-requirements.yml, bdd/helm-requirements.yaml.template, bdd/values.yaml.template, charts/lighthouse/Makefile, charts/lighthouse/templates/deployment.yaml, charts/lighthouse/templates/oauthsecret.yaml, charts/lighthouse/templates/tide-deployment.yaml, charts/lighthouse/values.yaml, jenkins-x-bbs.yml, jenkins-x-ghe.yml, jenkins-x-github.yml, jenkins-x-gitlab.yml, jenkins-x.yml
Down the road, this should change to pulling the token from vault dynamically, but we need the vault mutating webhook to make that work, so for now...tada.
Also, turns on vault and gitops for all contexts.
fixes #465
=> fix: Use token secret like Prow does

bdd/bbs/ci.sh, bdd/bbs/jx-requirements.yml, bdd/ghe/ci.sh, bdd/github/ci.sh, bdd/gitlab/ci.sh
Also re-enable chatops tests on GHE and GitHub with the right env var
name, and don't try running quickstart tests on BitBucket Server at
all due to the lack of labels there.
=> chore: Update BDD tests with extra log capturing

charts/lighthouse/templates/tide-role.yaml, pkg/tide/tide.go
At the least for kicking off PR builds after approval when they need a
rebuild, but I'd guess for master as well.
Also switched a log line to debug rather than info because it was
swamping the logs.
=> fix: Tide needs more permissions

pkg/prow/plugins/trigger/generic-comment.go, pkg/prow/plugins/trigger/trigger.go, pkg/prow/plugins/trigger/trigger_test.go
This is resulting in retest looking at contexts on master, not on the
PR, which is wrong and results in everything getting rebuilt.
fixes https://github.com/jenkins-x/jx/issues/6796
=> fix: retest and other checks need pr.Head.Ref, not pr.Base.Ref

pkg/webhook/webhook.go
The current verbosity overwhelms the logs thanks to issue and status
hooks, which we don't currently handle. Since we just use the exact
same hook configuration on GitHub as Prow would, we're getting those
whether we want them or not, and with #545 eventually we'll want
them. But for now, let's only vomit out all that noise on debug.
=> chore: Decrease verbosity of logging for unknown webhook kinds

pkg/prow/plugins/override/override.go, pkg/prow/plugins/override/override_test.go
This was an artifact of Prow overriding by creating a dummy job that
instantly passed, while we handle that directly.
fixes #557
=> fix: Override shouldn't create new builds

pkg/tide/tide.go
This isn't actually breaking anything right now, but still, let's be
more accurate.
=> fix: Simple state for running pipeline should be pending, not failure

pkg/tide/tide.go
There's no actual base sha mismatch when this log message reports one,
and the whole block just doesn't make sense, so let's clean it out.
=> chore: Remove pointless/confusing log message

bdd/github/ci.sh, bdd/github/jx-requirements.yml, jenkins-x-github.yml, jenkins-x.yml, pkg/plumber/plumber.go, pkg/plumber/test_data/convert/batch/expected.yaml, pkg/plumber/test_data/convert/presubmit/expected.yaml, pkg/plumber/types.go, pkg/prow/plugins/override/override.go, pkg/tide/tide.go, pkg/tide/tide_test.go, pkg/util/constants.go
This gets the user-facing behavior to more closely match Prow - `/override` creates a commit status with an `Overridden by ...` description, and even if the latest `PipelineActivity` for that context is failed or pending and hasn't reported since the `/override` went in, Tide should treat this context as successful/ready to merge.
In Prow, `/override` creates a new `ProwJob` - one that doesn't actually kick off a pipeline but just sets the commit status and sets its own status to successful. Since Prow uses `ProwJob`s as the "build status" source, where Lighthouse currently uses `PipelineActivity`s, Prow's Tide will see the override-created and successful `ProwJob` as the latest for the given context, rather than the created-earlier failed or pending `ProwJob`, and the PR (assuming all …
=> fix: overridden status takes precedence over latest build result

pkg/tide/githubapp/github_app_ctrl.go, pkg/util/constants.go
See https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation
=> fix: Use x-access-token as username in git client with GHA

bdd/values.yaml.template, charts/lighthouse/templates/deployment.yaml, charts/lighthouse/values.yaml, pkg/plumber/plumber.go
when using istio with helm 3 and lighthouse we need a way to use a different default image in meta pipeline client (as we need an image with helm 3 etc) so lets add a simple way to override the value via an environment variable.
this PR also fixes a bug in the indentation of allowing additional environment variables to be passed into the lighthouse `Deployment`
=> fix: allow the default jx image to be configured via helm

bdd/ghe/ci.sh, bdd/github/ci.sh
These are actually redundant now that we have `test-lighthouse`. And
let's use `test-create-spring` because we want to get the merge all
the way to prod.
=> chore: Remove app lifecycle tests

pkg/tide/githubapp/factory.go, pkg/tide/githubapp/github_app_ctrl.go
This ends up leaving a tmp directory with a clone of the version stream around for each Tide sync, which eventually overwhelms things and causes git operations to fail. There's no reason not to just create it once and reuse it.
=> fix: Don't recreate the metapipeline client for each GHA tide sync

pkg/watcher/configmap_watcher.go
I may want to rework this further, but the original watcher setup was not good at handling losing its connection. This should be better.
fixes #616
=> fix: Switch to using NewIndexInformerWatcher for webhook config

charts/lighthouse/templates/keeper-role.yaml
=> fix: Keeper needs permissions to create lighthouse jobs

charts/lighthouse/templates/keeper-deployment.yaml, charts/lighthouse/values.yaml, pkg/keeper/keeper.go, pkg/keeper/status.go, pkg/keeper/status_test.go
If the new `LIGHTHOUSE_KEEPER_STATUS_CONTEXT_LABEL` env var isn't set, it'll still be `keeper`, but if that is set, it'll be used instead. We'll now default it to `Lighthouse Merge Status` in the chart, but it can be overriden via the `keeper.statusContextLabel` value.
fixes #656
=> fix: Change default keeper status label and allow overriding

pkg/keeper/keeper.go, pkg/keeper/keeper_test.go, pkg/plugins/override/override.go
We're now using `LighthouseJob` for overrides, so we shouldn't need this any more.
fixes #678
=> fix: Get rid of live-check of SCM status for override

charts/lighthouse/templates/lighthousejobs-crd.yaml, charts/lighthouse/values.yaml
Like with Tekton, we need to make CRD creation optional to make it work with Openshift.
=> feat: make CRD creation optional

pkg/keeper/status.go
It doesn't go anywhere, so let's get rid of it. I'm leaving the `targetUrl` logic in here in case we end up wanting to revisit it in the future.
fixes #695
=> fix: Get rid of Deck link

charts/lighthouse/templates/hmacsecret.yaml, charts/lighthouse/templates/webhooks-deployment.yaml, go.mod, go.sum
This will fail until https://github.com/jenkins-x/jx/pull/7160 is merged and in the version stream.
fixes https://github.com/jenkins-x/jx/issues/7154
=> fix: Use Lighthouse-specific HMAC token secret name

pkg/scmprovider/reporter/reporter.go, pkg/scmprovider/reporter/reporter_test.go
Thanks to GitHub treating PRs and issues the same for a lot of things, we inherited this logic using `ListIssueComments`, but we should actually be using `ListPullRequestComments`.
=> fix: Failed pipeline report comments should use PR API, not issues

pkg/scmprovider/client.go, pkg/scmprovider/issues.go, pkg/scmprovider/pull_requests.go
Because we shouldn't be panicking in production, thanks.
=> fix: Switch SCM client panics to ErrNotSupported

bdd/bbs/ci.sh, pkg/plugins/approve/approve_test.go, pkg/plugins/lgtm/lgtm_test.go, pkg/plugins/wip/wip-label_test.go, pkg/scmprovider/client.go, pkg/scmprovider/issues.go, pkg/scmprovider/labels.go, pkg/scmprovider/pull_requests.go, pkg/scmprovider/test_helpers.go
Very, very, very super-preliminary. I need to add a bunch of more tests of the workaround logic for the hook side of adding/removing labels, and to Keeper's behavior as well. And I need to update `bdd-jx` to deal with this too. But hey, it's a start.
fixes #727
=> feat: BitBucket Server support via comments emulating labels

pkg/config/keeper.go, pkg/config/keeper_test.go
Using the `runIfChanged` JX scheduler field for pre- and post-submits (`run_if_changed` in the Prow/Lighthouse configuration for presubmits that we actually generate from the jx scheduler configuration) and the `alwaysRun` jx scheduler field, you can specify a regex in `runIfChanged` and `false` in `alwaysRun`, in which case the context will only run when the list of files changed in the PR matches the regex.
That's been in place for a while, but until this change, the jx scheduler->config generation would get things confused and make any context specified in `policy.requiredStatusContexts` be treated as required, whether it's automatically run/conditionally run/etc. This is largely because we kinda did things a bit dumb in how we generate the branch protection required status checks. …
=> fix: Support requiring for contexts with conditional execution

pkg/plugins/size/size.go
=> fix: Don't error out completely if .gitattributes doesn't exist

pkg/apis/lighthouse/v1alpha1/types.go, pkg/foghorn/controller.go, pkg/jx/activity.go, pkg/jx/activity_test.go, pkg/jx/helpers.go, pkg/jx/launcher.go, pkg/jx/test_data/lhjob.yaml, pkg/jx/test_data/pipelineactivity.yaml, pkg/jx/test_data/record.yaml, pkg/keeper/githubapp/factory.go, pkg/keeper/githubapp/github_app_ctrl.go, pkg/keeper/keeper.go, pkg/launcher/fake/fake.go, pkg/launcher/interface.go, pkg/plugins/override/override.go, pkg/plugins/plugins.go, pkg/plugins/trigger/push.go, pkg/plugins/trigger/trigger.go, pkg/record/record.go, pkg/util/constants.go, pkg/util/externalplugins.go, pkg/webhook/events.go, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go
Switch to a common activity record that we'll convert `PipelineActivity`s to, and report back based on that. This will also end up allowing us to send activity records to external plugins.
=> feat: Work towards supporting other engines besides jx

pkg/scmprovider/issues.go
=> fix: Stop using github.com/jenkins-x/jx/v2/pkg/log since it's going away

pkg/foghorn/controller.go
We had been comparing the owner label on the `PipelineActivity`, which is always lower case, but now we're comparing the `record.Owner`, which is coming from the `PipelineActivity.Spec.GitOwner`, which isn't forced to lowercase, so let's handle that properly.
fixes #832
=> fix: Lower-case owner/org in Foghorn job lookup

README.md
Looks like you got rid of the `prow/` prefix on packages at some point?
=> Fixing some 404s

go.sum, jenkins-x-bbs.yml, jenkins-x-ghe.yml, jenkins-x-github.yml, jenkins-x-gitlab.yml, jenkins-x.yml
Tekton 0.11 needs this change.
=> fix: Use $() instead of ${} in pipeline params

jenkins-x.yml
That can cause problems. There'll be a `make mod` soon (when https://github.com/jenkins-x/jx/pull/7487 merges), though, so let's use that.
=> fix: Don't make tidy-deps on jx

pkg/config/config.go, pkg/config/jobs.go, pkg/keeper/status.go, pkg/keeper/status_test.go, pkg/plugins/config.go, pkg/repoowners/repoowners.go, pkg/repoowners/repoowners_test.go, pkg/webhook/test_data/test_config.yaml, test/e2e/test_data/example-config.tmpl.yml
the `owners_dir_blacklist` field in the `config` `ConfigMap`, and the `labels_blacklist` field in the `plugins` `ConfigMap` should now change to `owners_dir_excludes` and `labels_excludes` respectively, but the existing fields will still function.
=> fix: Get rid of whitelist/blacklist terminology

pkg/engines/tekton/controller.go, pkg/engines/tekton/test_data/controller/start-pullrequest/expected-lhjob.yml, pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml, pkg/engines/tekton/test_data/controller/start-pullrequest/observed-lhjob.yml
=> feat(tekton): Set a default 24 hour timeout for created PipelineRuns

go.mod, go.sum, pkg/scmprovider/client.go
With go-scm 1.5.155, there's a GraphQL client for GitLab, but it won't actually work for our needs, so we need to change the check for when to use GraphQL to explicitly just be when we're on GitHub for now.
=> fix: Only use GraphQL for GitHub

pkg/engines/tekton/controller.go, pkg/engines/tekton/controller_test.go, pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-lhjob.yml, pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-pr.yml, pkg/engines/tekton/test_data/controller/start-batch-pullrequest/observed-lhjob.yml, pkg/engines/tekton/test_data/controller/start-batch-pullrequest/observed-pipeline.yml, pkg/jobutil/jobutil.go, pkg/jobutil/jobutil_test.go, pkg/keeper/keeper.go, pkg/keeper/keeper_test.go, pkg/plugins/override/override.go, pkg/plugins/override/override_test.go, pkg/plugins/trigger/trigger.go, pkg/scmprovider/client.go, pkg/scmprovider/fake/fake.go, test/e2e/tekton_test.go, test/e2e/test_data/tekton/pipelineAndTask.tmpl.yaml
Detect the `git-batch-merge` catalog `Task` and replace parameters as appropriate for this task as well as `git-clone`.
fixes #889
=> feat(tekton): Support git-batch-merge Task parameters

pkg/repoowners/repoowners.go
=> fix: Check if OwnersDirExcludes is non-nil before using it

charts/lighthouse/templates/plugins-cm.yaml
This PR fixes a missing argument in ne condition in the lighthouse helm chart 
Fixes #900
=> fix: Fix helm chart missing argument in ne condition

pkg/plugins/updateconfig/updateconfig.go, pkg/plugins/updateconfig/updateconfig_test.go
=> fix: Use the HEAD SHA for config updater check, since merge SHA may be empty

charts/lighthouse/.helmignore
This PR adds makefile and (potentially) OWNERS to helmignore.
There should be no point in adding the Makefile in helm package.
I added OWNERS too as it is common to have an OWNERS files.
=> chore: Add makefile and (potentially) OWNERS to helmignore

charts/lighthouse/templates/config-cm.yaml, charts/lighthouse/templates/plugins-cm.yaml, charts/lighthouse/values.yaml
This PR adds support for passing `config.yaml` and `plugins.yaml` directly to helm chart.
Two new parameters are added : `configMaps.config` and `configMaps.plugins`.
The chart can then be installed with:
```bash
helm install .... \
--set configMaps.create=true \
--set-file configMaps.config=./config.yaml \
--set-file configMaps.plugins=./plugins.yaml
```
/cc @abayer 
Closes #906
=> feat: Support passing config.yaml and plugins.yaml to helm chart

bdd/helm-requirements.yaml.template
The internal chartmuseum tends to explode lately for reasons I don't understand, but its contents are mirrored promptly enough to the public-facing one that we might as well just use that and avoid the pain.
=> fix: Stop using in-cluster chartmuseum in BDD requirements

charts/lighthouse/.helmignore, charts/lighthouse/Chart.yaml, charts/lighthouse/Makefile, charts/lighthouse/README.md, charts/lighthouse/README.md.gotmpl
This PR is a first step into getting docs for the helm chart.
This uses https://github.com/norwoodj/helm-docs to generate the docs.
It would be nice to be able to verify docs are up to date in the CI and maybe add docs gen in the makefile.
=> feat: Add helm docs

docs/PLUGINS.md
This PR initiates plugins documentation.
It has the plugins list, a brief description of the plugins.yaml file structure with an example of all stanzas and their use.
It will need more work to add documentation of each plugin, but this can be done in follow up PRs.
=> docs: Initiate plugins documentation

charts/lighthouse/templates/plugins-cm.yaml, pkg/plugins/config.go, pkg/repoconfig/merge/test_data/simple/expected-plugins.yaml, pkg/repoconfig/merge/test_data/simple/source-plugins.yaml, pkg/webhook/test_data/test_plugins.yaml, test/e2e/test_data/example-plugins.tmpl.yml
This PR removes `golint` and `blunderbuss` plugins config as they are not used in the code.
=> chore: Remove golint and blunderbuss plugins config (dead code)

docs/PLUGINS.md, docs/plugins/yuks.md
This PR adds yuks plugin docs.
I propose the following structure for plugin docs:
- Description
- Commands
- Configuration
- Compatibility matrix
I feel like those 4 sections will address most documentation aspects and having the same structure for all plugin docs helps improve docs quality.
I'm thinking about adding compatibility matrix to code also, it could be useful for porting plugins that are not compatible with all scm providers.
=> docs: Add yuks plugin docs

docs/plugins/yuks.md
This PR adds the `/lh-joke` command to the yuks plugin docs.
=> docs: Add lh-joke command to yuks plugin docs

pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-lhjob.yml, pkg/engines/tekton/test_data/controller/start-batch-pullrequest/observed-lhjob.yml, pkg/engines/tekton/test_data/controller/start-pullrequest/expected-lhjob.yml, pkg/engines/tekton/test_data/controller/start-pullrequest/observed-lhjob.yml, pkg/engines/tekton/utils.go, test/e2e/tekton_test.go
This PR wraps the payload passed to the template when resolving params in `pipeline_run_params`.
Instead of passing directly `spec.Refs` of the underlying `LighthouseJob`, it changes the payload to wrap `spec.Refs` into a `Refs` property.
This way, if we want to pass other data to the template it will be easier, just add a new property to the payload for the new data to be passed.
=> fix: Wrap payload passed to pipeline_run_params

pkg/engines/tekton/controller.go
This PR removes an obsolete property `tektonclient` in the tekton controller that i forgot to remove before merging.
=> chore: remove obsolete tektonclient in tektoncontroller

hack/generate-groups.sh
Like from 5m37s to 7s on my laptop. Turning off `GO111MODULE` makes for a huge improvement - see https://github.com/kubernetes/code-generator/issues/69
=> fix: Speed up codegen considerably

Makefile, crds/lighthouse.jenkins.io_lighthousejobs.yaml, pkg/apis/lighthouse/v1alpha1/types.go
This PR adds CRDs generation from types in `pkg/apis/lighthouse/v1alpha1`.
This adds CRD schema documentation.
=> feat: generate CRDs from types

cmd/foghorn/main.go, cmd/gc/main.go, cmd/tektoncontroller/main.go, pkg/clients/clients.go
This PR replaces `clients.GetConfig` with `clientcmd.BuildConfigFromFlags`.
Will require a change in the lighthouse-jx-controller too.
Closes #963
=> chore: replace clients.GetConfig with clientcmd.BuildConfigFromFlags

charts/lighthouse/templates/config-cm.yaml, charts/lighthouse/templates/keeper-deployment.yaml, cmd/keeper/main.go, pkg/config/agent.go, pkg/plugins/plugins.go, pkg/watcher/configmap_watcher.go
This'll keep it from failing to start if the configmaps aren't present and/or are malformed, and avoids the need for mounting the configmap as well.
And I fixed up the out-of-the-box `config` configmap to not be invalid.
=> chore: Switch Keeper to config map watcher

charts/lighthouse/README.md, charts/lighthouse/templates/tekton-controller-deployment.yaml, charts/lighthouse/values.yaml
This PR adds missing chart values for tekton controller (node selector, affinity, pod annotations, tolerations).
I also took the opportunity to reformat a little bit the deployment template to make it easier to read.
=> chore: add missing chart values for tekton controller

charts/lighthouse/templates/tekton-controller-role.yaml, cmd/tektoncontroller/main.go, pkg/engines/tekton/controller.go, pkg/engines/tekton/controller_test.go, pkg/engines/tekton/utils.go
This PR removes unnecessary rbac permissions to the tekton controller.
=> chore: tighten tekton controller rbac permissions

Dockerfile.jxcontroller
This PR removes two unused files `Dockerfile.jxcontroller` and `custom-boilerplate.go.txt`.
Not sure but `.helmignore` at the root of the repo could potentially be removed too.
=> chore: remove unused files

bdd/tekton/values.yaml.template, charts/lighthouse/README.md, charts/lighthouse/templates/webhooks-ingress.yaml, charts/lighthouse/values.yaml, test/e2e/helpers.go
This PR makes e2e tests non sensible to the ingress name.
The ingress is looked up by labels rather than by name.
=> chore: make e2e tests non sensible to the ingress name

pkg/engines/tekton/controller.go, pkg/engines/tekton/controller_test.go, pkg/engines/tekton/utils.go
fixes #950, replaces #951, relevant for #991 
=> chore: Switch Tekton engine build ID to epoch milliseconds

pkg/webhook/events.go, pkg/webhook/webhook.go
This PR makes webhook event handlers private (they don't need to be public)
=> chore: make webhook event handlers private

pkg/plugins/approve/approve.go, pkg/plugins/assign/assign.go, pkg/plugins/blockade/blockade.go, pkg/plugins/branchcleaner/branchcleaner.go, pkg/plugins/cat/cat.go, pkg/plugins/cherrypickunapproved/cherrypick-unapproved.go, pkg/plugins/dog/dog.go, pkg/plugins/help/help.go, pkg/plugins/hold/hold.go, pkg/plugins/label/label.go, pkg/plugins/lgtm/lgtm.go, pkg/plugins/lifecycle/lifecycle.go, pkg/plugins/milestone/milestone.go, pkg/plugins/milestonestatus/milestonestatus.go, pkg/plugins/override/override.go, pkg/plugins/owners-label/owners-label.go, pkg/plugins/plugins.go, pkg/plugins/pony/pony.go, pkg/plugins/shrug/shrug.go, pkg/plugins/sigmention/sigmention.go, pkg/plugins/size/size.go, pkg/plugins/skip/skip.go, pkg/plugins/stage/stage.go, pkg/plugins/trigger/trigger.go, pkg/plugins/updateconfig/updateconfig.go, pkg/plugins/welcome/welcome.go, pkg/plugins/wip/wip-label.go, pkg/plugins/yuks/yuks.go
This PR changes the way plugins register with the host.
Instead of an imperative approach, it uses a more declarative approach.
A plugin calls `RegisterPlugin` with a struct that describes the plugin handlers and other infos.
This will help having a clear contract between the host and the plugins and will allow to move some boilerplate code to the host progressively.
Moved into the `Plugin` descriptor struct:
- handlers
- description
=> refactor: Make RegisterPlugin more declarative

pkg/plugins/plugins.go, pkg/webhook/events.go
This PR replaces `GetXXXHandlers` methods by a single one `GetPlugins`.
The callers get the plugins and check if a handler is set for their specific needs.
=> chore: replace GetXXXHandlers methods by GetPlugins

pkg/plugins/approve/approve.go, pkg/plugins/blockade/blockade.go, pkg/plugins/blockade/blockade_test.go, pkg/plugins/wip/wip-label.go
This PR makes plugin name private in approve blockade and wip plugins.
=> chore: make plugin name private in approve blockade and wip plugins

pkg/plugins/dog/dog_test.go, pkg/plugins/label/label_test.go, pkg/plugins/milestonestatus/milestonestatus_test.go, pkg/plugins/override/override_test.go, pkg/plugins/plugins.go, pkg/plugins/pony/pony_test.go, pkg/plugins/shrug/shurg_test.go, pkg/plugins/sigmention/sigmention.go, pkg/plugins/stage/stage_test.go, pkg/plugins/yuks/yuks_test.go, pkg/webhook/events.go
This PR refactors the sigmention plugin.
The sigmention plugin does not follow the command concept, it catches all generic comment events and doesn't require matching a regex with a command like format.
To address this behavior i decoupled the `CommandEventHandler` and `GenericCommentEventHandler`. The former receives a regex match while the latter just receives the event and doesn't have an associated command help.
=> refactor: sigmention plugin

pkg/pluginhelp/pluginhelp.go, pkg/plugins/plugin.go, pkg/plugins/plugin_test.go, pkg/plugins/plugins.go, pkg/webhook/events.go
This PR adds scm providers exclusion support for plugins.
I also moved the `Plugin` struct to its own file and started adding unit tests.
I also added the `ExcludedProviders` field in the `PluginHelp` struct.
=> feat: add scm providers exclusion support to plugins

pkg/plugins/welcome/welcome.go, pkg/plugins/welcome/welcome_test.go, pkg/scmprovider/client.go, pkg/scmprovider/pull_requests.go
This PR makes the welcome plugin work.
The `FindIssues` method in the scm provider client is not implemented, i created a `FindPullRequestsByAuthor` method to be used by the welcome plugin.
=> fix: make welcome plugin work

pkg/triggerconfig/inrepo/calculate.go
if the ref "refs/origin/master" and we are processing "master" we load twice and possibly fail with duplicate contexts etc.
lets treat "master" and "refs/origin/master" as being effectively the same ref
=> fix: avoid processing the main branch twice

pkg/triggerconfig/inrepo/calculate_test.go, pkg/triggerconfig/inrepo/test_data/myorg/branchtest/refs/master/.lighthouse/triggers/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/branchtest/refs/mybranch/.lighthouse/triggers/triggers.yaml, pkg/triggerconfig/merge/merge.go
We merge presubmits or postsubmits by name when using shared configurations and in-repo configurations; or when using in-repo configurations on a particular branch versus master.
When merging triggers we need to make sure we combine them together if they have the same name; otherwise we end up with a configuration validation error with duplicate presubmits/postsubmits by name or for the same branch on a post submit
Without this fix, its quite easy to get lighthouse to fail to process a webhook if it has in-repo configurations as it ends up creating a duplicate Presubmit/Postsubmit and then refuses to process the webhook
=>  fix: merging postsubmits & presubmits together by name to avoid duplicates

docker/foghorn/Dockerfile, docker/gc/Dockerfile, docker/jenkins/Dockerfile, docker/keeper/Dockerfile, docker/tekton/Dockerfile, docker/webhooks/Dockerfile
While #1080 did what it was supposed to do (run as a non-root user), it didn't solve the problem I originally wanted to solve - have lighthouse run under a restrictive PodSecurityPolicy.
It currently fails with `container has runAsNonRoot and image has non-numeric user`.
From the official docs for MustRunAsNonRoot:
> Requires that the pod be submitted with a non-zero runAsUser or have the USER directive defined (**using a numeric UID**) in the image
=> fix: use numeric user for the image

charts/lighthouse/README.md, charts/lighthouse/values.yaml
the `webhooks` component needs to run the `git clone` command once for each repository. If you have big repositories, this could fail if you don't give enough memory to the container: the OOMKiller will kill the git process.
Let's used a "better" default value, and add a comment for people having the issue.
fixes:#1085
=> fix: bigger default memory limit for webhooks

pkg/triggerconfig/inrepo/calculate_test.go
It depended on the presubmit order, which meant it'd fail sporadically.
=> fix: Fix flaky calculate_test

pkg/config/config_test.go, pkg/config/job/config.go
we should be able to have multiple presubmit jobs with different names on the same branches. e.g. one job for linting, one for preview environments; or N jobs for different kinds of system/integration tests etc
=> fix: improve the validation of presubmit jobs

pkg/triggerconfig/inrepo/load_pipelinerun.go, pkg/triggerconfig/inrepo/load_pipelinerun_test.go, pkg/triggerconfig/inrepo/load_triggers.go, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/demo-deploy-kubectl.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/git-clone.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/kaniko.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/source.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/unit-tests.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/demo-deploy-kubectl.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/git-clone.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/kaniko.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/source.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/unit-tests.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/add-params.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/pipeline-with-extra-params.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/source.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr/source.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task/source.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/taskrun/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/taskrun/source.yaml
this PR makes it easier to reuse tekton catalog Tasks/Pipelines/PipelineRuns when using the in-repo mode so that...
* we can use either of PipelineRun/Pipeline/Task/TaskRun files for a `presumit` or `postsubmit` entry in the `source` property in the triggers.yaml (so that its easy to consume existing `Pipeline/Task/TaskRun` files without the user having to convert them to a `PipelineRun` first. This avoids the boilerplate required wrapping Tasks => Pipelines => PipelineRuns
* if reusing a combination of PipelineRun / Pipeline / TaskRun / Task files from the tekton catalog, allow Pipeline/Task refs to be resolved to inline PipelineSpec / TaskSpec structs to that the resulting PipelineRun for the lighthouse tekton engine is equivalent and the files read from git directly
both of these …
=> fix: improve tekton catalog integration

pkg/scmprovider/legacy_helpers.go, pkg/webhook/events.go
Hello, 
In https://github.com/jenkins-x/lighthouse/blob/08b0ae6ebc6a1feb4efafb2d77cae1149f151393/pkg/triggerconfig/inrepo/calculate.go#L48-L52 we add `eventRef` to the list of for for which we merge inrepoconfigs
But in a lot of case, `eventRef` is actually an empty string, because the agent created in pkg/webhook/events.go is given an empty string :
https://github.com/jenkins-x/lighthouse/blob/08b0ae6ebc6a1feb4efafb2d77cae1149f151393/pkg/webhook/events.go#L118
This PR makes it so that it is not the case anymore.
Please note that this is my first PR on this project and that I've not been using lighthouse for a very long time, so I might have missed a good reason for not doing this.
=> feat: Make inrepo config merge current PR branch config

pkg/triggerconfig/inrepo/default_parameters.go, pkg/triggerconfig/inrepo/load_pipelinerun.go, pkg/triggerconfig/inrepo/load_pipelinerun_test.go, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs-sub-dir/demo-deploy-kubectl.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs-sub-dir/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs-sub-dir/kaniko.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs-sub-dir/mydir/git-clone.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs-sub-dir/source.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs-sub-dir/unit-tests.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-missing-refs-fails/source.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-append-steps/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-append-steps/source.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-prepend-steps/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-prepend-steps/source.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-without-params/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-without-params/source.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/taskrun/expected.yaml
we should not default `$(params.FOO)` values for `PipelineRun.Spec.Params` since those expressions only make sense inside a Pipeline/Task and the values are usually specified via `pipeline_run_params` or by Lighthouse when it defaults parameters like REPO_URL and so forth
fixes https://github.com/jenkins-x/lighthouse/issues/1122
there's really no need to copy/paste the 150 lines of YAML for all the common lighthouse based parameters that get injected...
https://github.com/jenkins-x/jx3-pipeline-catalog/blob/master/packs/go-plugin/.lighthouse/jenkins-x/release.yaml#L9-L159
we can just enrich the `PipelineRun` and add them in if they are not already there
=> fix: avoid lots of boilerplate YAML for in-repo PipelineRuns

pkg/engines/tekton/controller.go, pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-pr.yml, pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml, pkg/engines/tekton/test_data/controller/start-push/expected-pr.yml
avoid setting `blockOwnerDeletion: true` on the `PipelineRun` to avoid failing on OpenShift 4.x
fixes #1143
=> fix: fix for OpenShift 4.x

charts/lighthouse/README.md, charts/lighthouse/templates/webhooks-deployment.yaml, charts/lighthouse/values.yaml, pkg/plugins/trigger/trigger.go
deployments can configure the ability to allow custom lighthouse triggers using their own unique chat prefix,
for example extending the default `/test` trigger prefix let them specify the helm chart value
```
webhooks.customDeploymentTriggerCommand=foo
````
which means they can also use their own custom trigger /foo mycoolthing
fixes #1145
=> feat: handle custom trigger commands for a deployment

pkg/engines/tekton/controller.go, pkg/engines/tekton/controller_test.go, pkg/engines/tekton/test_data/controller/update-job/observed-lhjob.yml
we've seen some failures + some pipelines not started due to update errors so lets add a retry loop
=> fix: add retry handler to updating lighthousejobs

charts/lighthouse/templates/jenkins-controller-secret.yaml
fixes https://github.com/jenkins-x/lighthouse/issues/1150
=> chore: lets only create the jenkins controller secret when the jenkins engine is enabled like the other jenkins specific k8s resources

charts/lighthouse/templates/foghorn-deployment.yaml
which results in activity records events sent to external plugin not being signed with the right token
=> fix(chart): foghorn is missing the HMAC token

pkg/triggerconfig/inrepo/calculate.go, pkg/webhook/webhook.go
file browser couldn't read serverUrl
allow fallback to current ref when main branch doesn't have triggers
=> fix: file browser couldn't read serverUrl

pkg/config/job/regexpchangematcher.go
What:
when using `run_if_changed`  it always crashes
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x758982]
[running]:
regexp.(*Regexp).doExecute(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000519c20, 0
x1d, 0x0, 0x0, ...)
/usr/local/go/src/regexp/exec.go:527 +0x562
regexp.(*Regexp).doMatch(...)
/usr/local/go/src/regexp/exec.go:514
regexp.(*Regexp).MatchString(...)
/usr/local/go/src/regexp/regexp.go:507
github.com/jenkins-x/lighthouse/pkg/config/job.RegexpChangeMatcher.RunsAgainstChanges(0xc0008641c0, 0x12, 0x0, 0xc000341680, 0x8, 0x8, 0x0)
```
How
adds function GetRE and call MatchString via it
Why 
to make sure that regex is not nil when calling MatchString
=> fix: race condition that call reChanges with nil regex

cmd/webhooks/main.go, pkg/webhook/metrics.go, pkg/webhook/webhook.go
for webhook counts per event kind so its easier to know if lighthouse has been setup correctly and webhooks are being received
I've used`/Metrics` as the endpoint to follow the naming convention with `/Health` and `/Ready`
=> fix: expose prometheus metrics

cmd/webhooks/main.go
=> fix: Typo fixed '7Path' to 'Path' in cli args help

pkg/triggerconfig/inrepo/test_data/myorg/branchtest/refs/master/.lighthouse/triggers/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/branchtest/refs/mybranch/.lighthouse/triggers/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/duplicate-postsubmit/.lighthouse/duplicate-lint/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/duplicate-postsubmit/.lighthouse/linter/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/duplicate-presubmit/.lighthouse/duplicate-lint/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/duplicate-presubmit/.lighthouse/linter/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/loadtest/.lighthouse/jenkins-x/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/loadtest/.lighthouse/linter/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/myrepo/.lighthouse/jenkins-x/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/myrepo/.lighthouse/linter/triggers.yaml, pkg/triggerconfig/merge/merge.go, pkg/triggerconfig/merge/merge_test.go, pkg/triggerconfig/merge/test_data/simple/expected-config.yaml, pkg/triggerconfig/merge/test_data/simple/triggers.yaml
The problem found when user specified `run_if_changed` in triggers.yaml. It can make lighthouse crash with nil pointer dereference panic because `run_if_changed` required to compile regular expression before use it. The workaround for this problem fixed in https://github.com/jenkins-x/lighthouse/commit/ff0c2cb55ba0b184a4059fe5f0877a2a33f2f3de. After dig down into the problem, I found that configuration doesn't initialize before validate (ref this function call https://github.com/wingyplus/lighthouse/blob/25e654ab141d8280b97c4aa9c7e9279a0d35fe12/pkg/triggerconfig/merge/merge.go#L87). So try fix it by add `cfg.Init` before `cfg.Validate` calls. 
After adding Init function calls. I found that tests was fail due to `rerun_command` doesn't be the subset of `trigger` and field name is …
=> fix: build pull request broken when run_if_changed is set

Makefile, bdd/gitea/ci.sh, bdd/gitea/gitea.values.yaml.template, bdd/gitea/user.template.json, bdd/gitea/values.yaml.template, jenkins-x-gitea.yml, pkg/git/git.go, pkg/keeper/keeper.go, pkg/plugins/approve/approvers/owners.go, pkg/repoowners/repoowners.go, pkg/util/scmclient.go, test/e2e/helpers.go
Yay! Gitea 1.13 finally released, so this is ready to go. =)
=> feat: Tests/official support for Gitea

.gitignore, go.mod, go.sum
The gitea client prior to this upgrade uses `/repos/%s/%s/commits/%s/status` which results in an error in lighthouse keeper
```
lighthouse-keeper-69969c4cff-98j8v lighthouse-keeper {"component":"keeper","controller":"status-update","error":"failed to get the combined status: unexpected end of JSON input","file":"/workspace/source/pkg/keeper/status.go:326","func":"github.com/jenkins-x/lighthouse/pkg/keeper.(*statusController).setStatuses.func1","level":"error","msg":"Getting head commit status contexts, skipping...","org":"coders","pr":1,"repo":"jx3-cluster-repo","sha":"83ab6c85f6953abb9995cc09c0081b46ad007e93","time":"2020-12-30T11:10:39Z"}
```
This is because the server is expecting the url to be `/repos/%s/%s/commits/%s/statuses`
=> fix: upgrade gitea client fix get combined status

pkg/filebrowser/git_file_browser.go
fixes https://github.com/jenkins-x/lighthouse/issues/1191
=> fix: return the err to prevent a panic below when client.repoClient is nil

pkg/triggerconfig/inrepo/load_integration_test.go, pkg/triggerconfig/inrepo/test_data/myorg/loadtest/.lighthouse/jenkins-x/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/loadtest/.lighthouse/linter/triggers.yaml, pkg/triggerconfig/merge/merge.go
lots of in-repo triggers have incorrectly used `/test` and `/retest` and `/lint` and `/relint` for `trigger` and `rerun_command` due to the bug where we didn't used to properly validate JobConfig for in repo.
to make it easy to transition to the latest lighthouse lets add a little migrator function to switch those bad configurations to their correct values so that lighthouse still works if its upgraded for existing triggers in Jenkins X
=> fix: convert old incorrect configuration

pkg/jobutil/jobutil.go
Trying to fix #1210
Not sure if this is all that's needed. Oddly there already seems to be tests that check for extra annotations. I'm guessing because this is a util function that isn't used in the test, but I'm not familiar enough with go to know how to check the coverage.
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
=> fix: get annotations as from jobutil.LabelsAndAnnotations

docs/pipelines.md, pkg/filebrowser/file_browsers.go, pkg/filebrowser/file_browsers_test.go, pkg/keeper/githubapp/factory.go, pkg/keeper/githubapp/github_app_ctrl.go, pkg/keeper/keeper.go, pkg/triggerconfig/inrepo/calculate.go, pkg/triggerconfig/inrepo/calculate_test.go, pkg/triggerconfig/inrepo/git_uri.go, pkg/triggerconfig/inrepo/git_uri_test.go, pkg/triggerconfig/inrepo/load_integration_test.go, pkg/triggerconfig/inrepo/load_pipelinerun_test.go, pkg/triggerconfig/inrepo/load_triggers.go, pkg/triggerconfig/inrepo/load_triggers_test.go, pkg/triggerconfig/inrepo/resolver_cache.go, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-custom-git/README.md, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-custom-git/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-custom-git/source.yaml, pkg/triggerconfig/inrepo/uses_resolver.go, pkg/webhook/create_agent.go, pkg/webhook/events.go, pkg/webhook/webhook.go
folks may want to reuse from github.com for things like tekton catalog: `uses:tektoncd/catalog/task/git-clone/0.2/git-clone.yaml@HEAD` while also using files from the current git server (if not using github.com as the git server)
so lets add an optional `uses:(lighthouse:)owner/repository/path@version` syntax to reference the lighthouse git server instead of github.com
=> fix: add support multiple git servers in uses:sourceURI

pkg/config/lighthouse/config.go, pkg/triggerconfig/inrepo/calculate.go, pkg/triggerconfig/inrepo/load_pipelinerun.go
this helps when investigating issues where repo names might have been changed and there's no matching in repo LH config
=> chore: add logging to help know if in repo is being used, also fixed issue with an in-repo error being swallowed

charts/lighthouse/README.md, charts/lighthouse/templates/keeper-deployment.yaml, charts/lighthouse/templates/webhooks-deployment.yaml, charts/lighthouse/values.yaml, cmd/keeper/main.go, pkg/metrics/metrics.go
- ensure prometheus metrics are exposed if required
- fix chart to allow users to add the prometheus scrape annotations on the pods
=> fix: prometheus support for keeper

pkg/triggerconfig/inrepo/load_pipelinerun_test.go, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/README.md, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/common.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/expected2.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/source.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/source2.yaml, pkg/triggerconfig/inrepo/uses_resolver.go
The test runner was changed to evaluate multiple source/expected runs
e.g. 
source.yaml compared to expected.yaml
source2.yaml compared to expected2.yaml
Fix was a `pr.DeepClone()`
Fixes https://github.com/jenkins-x/lighthouse/issues/1234
=> fix: in uses resolver, clone pipelinerun when returning from the cache to avoid changes persistng between evaluations

pkg/keeper/keeper.go
so that we log if keeper creates a LH job
=> chore: add more logging

charts/lighthouse/README.md, charts/lighthouse/config/lighthousejobs.lighthouse.jenkins.io-v1.yaml, charts/lighthouse/templates/lighthousejobs-crd.yaml
lets allow v1 of CRDs to be used in more recent k8s installs
=> fix: handle v1 CRDs

charts/lighthouse/templates/webhooks-deployment.yaml
the chart should only render the pod annotations if they are not null/empty
=> fix: helm chart webhook pod annotations

.lighthouse/jenkins-x/release.yaml, pkg/engines/tekton/test_data/controller/start-pullrequest/expected-lhjob.yml, pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml, pkg/engines/tekton/test_data/controller/start-pullrequest/observed-lhjob.yml, pkg/jobutil/jobutil.go, pkg/jobutil/jobutil_test.go
lets add a rebased version of this PR https://github.com/jenkins-x/lighthouse/pull/1156 to get it past the new CI setup
fixes #1155
add missing PipelineRunParams in specFromJobBase add corresponding test
=> fix: add missing PipelineRunParams when creating LighthouseJobSpec from job.Base

pkg/filebrowser/git_file_browser_test.go, pkg/git/v2/interactor.go, pkg/git/v2/interactor_test.go
If I run a pipeline that has a uses: line with an @version suffix, then change the pipeline to have a later @version suffix and re-trigger, I get this error
```
{"Branch":"master","Clone":"https://git.drivenow.com.au/drivenow/octane-staging.git","ID":"2206","Link":"https://git.drivenow.com.au/drivenow/octane-staging","Name":"octane-staging","Namespace":"drivenow","Webhook":"push","error":"failed to create agent: failed to calculate in repo config: failed to load trigger config for repository drivenow/octane-staging for ref ad417c592f9a80ca5c559d41885b3e96f07b3a6b: failed to load file .lighthouse/jenkins-x/triggers.yaml in drivenow/octane-staging with sha ad417c592f9a80ca5c559d41885b3e96f07b3a6b: failed to load source for presubmit pr: failed to unmarshal YAML file …
```
=> fix: include tags when fetching updates from the server

pkg/util/externalplugins.go
related to https://github.com/jenkins-x/jx3-versions/pull/2307
if we have external plugins that can't be reached, let's just log this as a warning, because it's not impacting the behaviour of lighthouse in itself.
=> fix: log at warning level when external plugin failed

pkg/webhook/events.go
previously issues & pullrequests comments used the issue/pr ID as the event GUID
related to https://github.com/jenkins-x/go-scm/pull/267
=> fix: use the right event GUID when handling comments

pkg/jobutil/jobutil.go
when copying lhjob annotations to other resources, we need to ensure that some of them won't be copied:
the annotations holding the opentelemetry trace context
these are used by https://github.com/jenkins-x/lighthouse-telemetry-plugin to propagate the trace context between different resources (lhjob, pipelinerun, pipelinetask, pod, activity, ...) and should be unique for each resource
=> chore: ensure opentelemetry annotations are not copied

go.sum, pkg/triggerconfig/inrepo/calculate_test.go, pkg/triggerconfig/inrepo/resolver_cache.go, pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/master/.lighthouse/jenkins-x/pullrequest.yaml, pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/master/.lighthouse/jenkins-x/shared-task.yaml, pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/master/.lighthouse/jenkins-x/triggers.yaml, pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/pr1/.lighthouse/jenkins-x/pullrequest.yaml, pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/pr1/.lighthouse/jenkins-x/shared-task.yaml, pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/pr1/.lighthouse/jenkins-x/triggers.yaml, pkg/triggerconfig/inrepo/uses_resolver.go
Test case in TestUsesInPRBranch, test data in pkg/triggerconfig/inrepo/test_data/myorg/uses-cache-issue
The fix was to include the SHA in the uses resolver cache key so that a different entry exists for master and the pr branch for a given path.
=> fix: fix uses resolver using incorrect version of uses:task.yaml

pkg/webhook/events.go
ensure we won't log the following error when handling draft PRs switching to the "ready for review" state:
Could not coerce pull_request event to a GenericCommentEvent. Unknown 'action': "ready_for_review".
by adding the missing actions to the list of actions that are not related to a PR comment
=> fix: handling draft PRs without errors

.lighthouse/jenkins-x/release.yaml, charts/lighthouse/values.yaml
ghcr.io/jenkins-x/xxx:0.0.750 does not exist
=> chore: bump the image tag from 0.0.750 to 1.1.0

pkg/keeper/status.go
the `TargetURL` defined in the keeper config was not used when pushing status update to the git provider, but now that we have a lighthouse web UI at https://github.com/jenkins-x-plugins/lighthouse-webui-plugin we should use it
I'll also update the versions stream to use the new LH webui instead of the pipelines visualizer
=> fix(keeper): use the target URL when updating status

pkg/plugins/updateconfig/updateconfig.go, pkg/webhook/events.go
fix that config-updater not work with gitlab, because of not dealing with ActionMerge event
=> fix: config-updater not work with gitlab

pkg/keeper/githubapp/factory.go
Fix scm client authentication failure for bitbucket cloud
=> fix: correct BBC scm client authentication for keeper

pkg/keeper/status.go
For BBC add valid URL for status reports
=> fix: Bit Bucket Cloud requires a valid URL in all status reports

pkg/config/job/presubmit.go, pkg/triggerconfig/inrepo/load_triggers_test.go
so that we can prevent auto merge on a PR for any contexts with `always_run: false` if they have `require_run: true`
=> fix: add a new require_run property

pkg/plugins/lgtm/lgtm.go
- fall back to commit.sha if commit.Tree.sha is empty (gitlab only provides commit.sha)
=> fix: fall back to commit.sha if commit.Tree.sha is empty

pkg/poller/poller.go, pkg/poller/pollstate/interface.go, pkg/poller/pollstate/memory.go
In the current poller implementation, if an event fails to be delivered (for example, if the Lighthouse hook is down), the poller does not retry. This PR invalidates the cache on error so that the poller will retry.
=> feat: Invalidate failed polls

charts/lighthouse/templates/poller-deployment.yaml, charts/lighthouse/values.yaml, cmd/poller/main.go, pkg/poller/poller.go, pkg/poller/poller_test.go
If there are multiple CI jobs running against the same repository, poller may think that the Lighthouse job has run, when actually it was another system (e.g. Jenkins). This PR adds support for a flag to supply a regex pattern for matching the commit status context so that poller is looking for signs of the correct job.
=> feat: Support commit context match pattern

pkg/plugins/label/label.go, pkg/plugins/label/label_test.go
We are using a general term of 'team' so we would like to leverage the team label in the label plugin
=> feat: add 'team' label to labels plugin

charts/lighthouse/README.md, charts/lighthouse/templates/gc-jobs-cj.yaml, charts/lighthouse/values.yaml
- Add backoff limit for cron job to override the default of 6 if needed
=> feat: Add backoff limit for cron job

charts/lighthouse/templates/poller-deployment.yaml, charts/lighthouse/values.yaml, cmd/poller/main.go, pkg/poller/poller.go, pkg/poller/poller_test.go
Adds a flag to keeping polling releases until the commit status is successful. This can be useful if you always expect releases to succeed.
The main issue with this implementation is that a more recent poll might overwrite an already successful status if the jobs overlap, causing unnecessary/continuous polling (since the go-scm library [only exposes the most recent status](https://github.com/jenkins-x/go-scm/blob/e6613ef378a644b1c464409a88d27f59484fffa8/scm/driver/github/repo.go#L462-L465) for a particular context) so the user needs to ensure the poll interval is long enough to reduce the chance of this happening (e.g. longer than the job timeout). I have created an issue and a WIP PR to allow go-scm to support fixing this issue (for GitHub at least): …
=> feat: Support poller require release success

charts/lighthouse/templates/keeper-role.yaml
- do not include tekton roles when tekton engine is disabled
=> fix: do not include tekton roles when disabled

pkg/poller/poller.go, pkg/poller/poller_test.go
This PR ensures that Lighthouse poller finds all statuses when polling instead of just using the first page
=> fix: Page through statuses when polling

pkg/util/scmclient.go, test/e2e/helpers.go
for example this URL is the URL to the readme in the gitea go-sdk,
https://gitea.com/gitea/go-sdk/src/branch/master/README.md
The format uses `src/branch` and not blob like GitHub.
=> fix: correct url for gitea blobs

pkg/filebrowser/fake/fake_file_browser.go, pkg/filebrowser/git_file_browser.go, pkg/filebrowser/interface.go, pkg/git/git.go, pkg/git/v2/client_factory.go, pkg/git/v2/interactor.go, pkg/git/v2/interactor_test.go, pkg/git/v2/no_mirror_client_factory.go, pkg/plugins/approve/approvers/owners.go, pkg/plugins/command_test.go, pkg/plugins/trigger/trigger.go, pkg/poller/poller.go, pkg/repoowners/repoowners.go, pkg/triggerconfig/inrepo/load_triggers.go, pkg/webhook/events.go
Sparse checkout is implemented especially for handling webhooks.
I have also changed to shallow clones even if you don't opt in to sparse checkout.
For now sparse checkout is enabled by setting the environment variable SPARSE_CHECKOUT=true.
I'm in the process of testing this in our own dev cluster now.
This is a part of solving jenkins-x/jx#8240
=> feat: Sparse checkout

Makefile, pkg/config/job/config.go, pkg/config/job/presubmit.go, pkg/jobutil/filter.go, pkg/plugins/trigger/generic-comment.go
ignore changes are not ignored if always_run is set to true.
So even if the user wants to not trigger a build when README file is changed for example, lighthouse will still trigger a build because always_run is evaluated first in the logic.
Context: https://kubernetes.slack.com/archives/C9MBGQJRH/p1657794048005119
=> fix: evaluate ignoreChanges before checking if pre-submit should always run

go.mod, go.sum
make test error
```
./command_test.go:424:5: (*testing.common).Errorf does not support error-wrapping directive %w
FAIL	github.com/jenkins-x/lighthouse/pkg/plugins [build failed]
```
Replacing `%w` with `%v`
=> fix: Errorf does not support error-wrapping

go.mod, go.sum
go-scm v1.11.32 includes the following fix: https://github.com/jenkins-x/go-scm/pull/321
=> feat: Bump go-scm to v1.11.32

.lighthouse/jenkins-x/release.yaml, charts/lighthouse/templates/keeper-deployment.yaml, charts/lighthouse/templates/poller-deployment.yaml
Reverts jenkins-x/lighthouse#1503
Test successful.
Can be reverted when jx-updatebut is upgraded to this (or later) version in the version stream.
=> Revert "fix: Make release work"

charts/lighthouse/templates/foghorn-deployment.yaml, charts/lighthouse/templates/poller-deployment.yaml, charts/lighthouse/templates/webhooks-deployment.yaml, charts/lighthouse/values.yaml, cmd/poller/main.go, pkg/util/scmclient.go, pkg/util/scmclient_test.go, pkg/util/test_data/secret_dir/hmac-token
Similarly to https://github.com/jenkins-x/lighthouse/pull/1511 some highly restricted environments do not allow secrets to be supplied via environment variables since they are a common attack vector.
This PR adds support for reading the HMAC token from a path supplied through an environment variable `HMAC_TOKEN_PATH`. Corresponding tests and a Helm chart option `hmacTokenVolumeMount.enabled` have also been added.
Backwards compatibility is maintained by looking for the `HMAC_TOKEN` environment variable first.
@ankitm123 I tried to add table driven tests as suggested in https://github.com/jenkins-x/lighthouse/pull/1511. Not sure if the tests in this PR is what you meant? If they are then I can add them for https://github.com/jenkins-x/lighthouse/pull/1511 in a subsequent PR
=> feat: Add support for HMAC token volume

.lighthouse/jenkins-x/release.yaml
Background: the jx-changelog image isn't built anymore. The problem with it was that the jx command downloaded jx-changelog on the first invokation, even though it was already in the image. So the jx-boot image is recommended instead; it doesn't have that problem.
also cleaning up a bit
=> fix: use jx-boot image for changelog

pkg/plugins/label/label.go, pkg/plugins/label/label_test.go
Add a `risk` label to allow assigning an impact label to merge requests. This provides an easy view of the overall impact of a change request and can faciliate the risk of multiple low vs high risk changes into a single code release.
=> feat: Add risk label

pkg/triggerconfig/inrepo/params.go, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-params-from-tasks-results/expected.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-params-from-tasks-results/save-results-task.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-params-from-tasks-results/show-results-task.yaml, pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-params-from-tasks-results/source.yaml, pkg/triggerconfig/inrepo/uses_resolver.go
Hello,
I first want to thank you so much for the help to allow the upgrade to 1.25 @tomhobson @msvticket and all others i'm forgetting.
I am using params with as value the results from previous tasks.
It worked in jx 3.10.83, but since I have upgraded to 3.10.86 in order to upgrade my cluster to 1.25 it broke
I know that jx uses resolver will be removed, but in order to prepare the right way, I need to keep a little more the uses inside my jx3 catalog, and so this PR would help be a lot.
I was able to reproduce with this PipelineRun that is generated after `jx uses` resolver.
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
name: jx3-test-save-show-results
spec:
pipelineSpec:
tasks:
- name: save-results
params:
- name: value_to_save
value: "test_demo"
taskSpec:
params:
- …
```
=> fix: allow params from previous tasks results

charts/lighthouse/templates/tide-githubapp-secrets.yaml
Brings the github app secret inline with the other secrets created by lighthouse
=> fix: add labels to tide-github-app secret

pkg/keeper/keeper.go, pkg/keeper/keeper_test.go
We can get the pull requests `baseRefSha` from the graphql query, this should reduce the rate limit usage as we no longer need to hit the rest api for every PR returned by the initial graphql query. This also reduces the rate consumption for scms that don't support graphql as `baseRefSha` is already found in the initial rest query.
=> fix: get the baseRefSha from graphql to reduce rate consumption

pkg/config/job/presubmit.go, pkg/jobutil/filter.go, pkg/plugins/trigger/generic-comment.go, pkg/plugins/trigger/generic-comment_test.go, pkg/scmprovider/pull_requests.go
You couldn't trigger pipelines with /test if they had branches specified. This is fixed with this PR. There where commented out tests that failed without this fix.
I let the trace logs be. They might be useful some other time.
=> fix: make /test work with branches

pkg/foghorn/controller.go
We are using Lighthouse foghorn v1.14.4 and very occasionally it is getting into a continuous loop trying to update a LighthouseJob when there is a conflict.
Initially there is a failure with the following message:
```
Failed to update LighthouseJob status: Operation cannot be fulfilled on lighthousejobs.lighthouse.jenkins.io "[LIGHTHOUSE_JOB_NAME]": the object has been modified; please apply your changes to the latest version and try again
```
It does try again and succeeds: `took 2 attempts to update Job`
However, I think this is false positive because `jobCopy` (instead of `&job`) is being passed into `retryModifyJob` so on retry `r.client.Get` is overwriting `jobCopy` and reverting the updated status, meaning the retry is just updating the LighthouseJob to its current value.
This PR …
=> fix: Retry foghorn LighthouseJob update using original variable instead of DeepCopy variable

docs/config/plugins/github-com-jenkins-x-lighthouse-pkg-plugins.md, docs/install_lighthouse_with_tekton.md, docs/plugins/Plugins config.md, pkg/plugins/config.go, pkg/plugins/trigger/generic-comment.go, pkg/plugins/trigger/pull-request.go, pkg/plugins/trigger/pull-request_test.go, pkg/plugins/trigger/trigger.go
related to https://github.com/jenkins-x/lighthouse/pull/1476 && https://github.com/jenkins-x/lighthouse/issues/886
:warning: Once this PR merged we will need to 
- wait for lighthouse-client update
- update this jx-gitops PR: https://github.com/jenkins-x-plugins/jx-gitops/pull/953
Context: 
- We can't add label when opening a PR so we can only Draft a PR to disable the trigger of pipelines in case we need massive batch opening of PRs in 100+ repositories for instance . 
- Then we can activate manually the pipelines by clicking on 'Ready for Review' or commenting `/ok-to-test` from a trusted member
How to enable this feature ?
Add `skip_draft_pr` feature on the Trigger Plug-in from you scheduler:
- setup `skip_draft_pr` in scheduler trigger like `only_org_members` to allow easy migration …
=> feat: allow to skip draft prs unless ready for review or /ok-to-test is added

pkg/engines/tekton/utils.go
allows us to use the native tekton pipelineRef git resolver
```
pipelineRef:
resolver: git
params:
- name: repo
value: xxx
- name: revision
value: main
- name: pathInRepo
value: /path/to/pipeline.yaml
```
in such case, our pipelineRef.name is empty, but it's not an error
=> chore: allows use of tekton pipelineRef.Resolver

docs/config/plugins/github-com-jenkins-x-lighthouse-pkg-plugins.md, docs/plugins/Plugins config.md, pkg/plugins/config.go, pkg/plugins/trigger/trigger.go, pkg/plugins/trigger/trigger_test.go
Currently, the way Lighthouse work doesn't allow us to automatically trigger PRs pipelines when the PR is created by a Github App.
This behaviour is related to the fact that Lighthouse trigger pipelines only for [trusted PRs authors](https://github.com/jenkins-x/lighthouse/blob/main/pkg/plugins/trigger/pull-request.go#L48-L58). [Trusted authors](https://github.com/jenkins-x/lighthouse/blob/main/pkg/plugins/trigger/trigger.go#L187-L229) being either the [collaborators of the repository](https://github.com/jenkins-x/go-scm/blob/1e8a1891da590c07e24075afe8748483d74e9705/scm/driver/github/repo.go#L100-L130) or the [members of the organization](https://github.com/jenkins-x/go-scm/blob/1e8a1891da590c07e24075afe8748483d74e9705/scm/driver/github/org.go#L74-L90). However, Github apps can't be in …
=> feat: allow to list trusted apps

docs/config/plugins/github-com-jenkins-x-lighthouse-pkg-plugins.md, docs/plugins/Plugins config.md, pkg/foghorn/controller.go, pkg/plugins/config.go
This PR is intended to allow you to bypass the reporting running/pending status done in the Forghon controller.
This mean the SCM Status won't change if previous status was (Running/Pending) and your current is still (Running/Pending).
Also with this option enabled we don't use anymore the Running Stages in the description like
- Pipeline running stage(s): from-buil
We are now only using this kind of pipeline status:
- Pending - Pipeline running
- Pipeline failed
- Pipeline successfull
The need behind this feature is to limit calls to SCM API and avoid rate limiting issues.
=> feat: skip running status (running/pending) if last state

charts/lighthouse/templates/webhooks-service.yaml, charts/lighthouse/values.yaml
Makes it possible to only allow traffic from certain source ranges.
Typical use case would be if the ingress load balancer is internal and you only have an external network load balancer for the hook.
=> feat: support loadBalancerSourceRanges for hook

pkg/keeper/keeper.go, pkg/keeper/keeper_test.go, pkg/keeper/status_test.go
The baseRefOID field is used as the sha of the base ref. The problem is that the returned value for this field sometimes is another sha. Often I think it is the sha of the base when the PR was created, but sometimes it is the sha of a much older commit. 
In this PR I replace the use of baseRefIOD with 
```
baseRef {
target {
oid
}
}
```
This seems to always be the current sha of the base ref, which is what we want.
This should fix the issue reported here: https://kubernetes.slack.com/archives/C9MBGQJRH/p1728050746717079
=> fix: base ref

pkg/engines/tekton/controller.go
Apparently some race condition made this change cause multiple lighthouse jobs being creating
Reverting jenkins-x/lighthouse#1619
=> revert: retry creation of pipelinerun

go.mod, go.sum, pkg/keeper/keeper_test.go, pkg/plugins/trigger/periodic.go, pkg/scmprovider/content.go
Latest go-scm add `ListOptions` to `Contents.List` interface (https://github.com/jenkins-x/go-scm/pull/470). Added an empty `ListOptions` to satisfy the interface & update go-scm.
Resolves broken PRs https://github.com/jenkins-x/lighthouse/pull/1634.
=> chore(deps): update go-scm

pkg/plugins/approve/approve_test.go, pkg/plugins/approve/approvers/approvers_test.go, pkg/plugins/approve/approvers/owners.go
Currently the rendered HTML on gitlab is confusing:
```
This pull-request has been approved by: To complete the pull request process, please assign <user> You can assign the PR to them by writing /lh-assign @<user> in a comment when ready.
```
The above content are in one paragraph without new lines or `.`.
Tweak according to [CommonMark Spec][1], since both [GitHub Flavored Markdown Spec][2] and [GitLab Flavored Markdown][3] are based on it.
[1]: https://spec.commonmark.org/0.31.2/#hard-line-breaks
[2]: https://github.github.com/gfm/#hard-line-breaks
[3]: https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/user/markdown.md#newlines
Gitlab before:
Gitlab after:
=> chore: Tweak APPROVALNOTIFIER markdown template to render consistent HTML

docs/config/plugins/github-com-jenkins-x-lighthouse-pkg-plugins.md, docs/plugins/Plugins config.md, pkg/foghorn/controller.go, pkg/plugins/config.go
This PR is intended to allow you to show completion duration in the description of the report done in the Forghon controller while keeping the SCM status.
example :
=> feat: allow display report completion duration
